/**
 * agw_hero_viz.js — AGW landing-page hero visualization
 * ─────────────────────────────────────────────────────────────────────────
 * "Denkschulen-Konstellation" — production build on the validated corpus.
 *   • node size  = prominence.factor (the validated PC1 scalar)
 *   • edges      = body-only co-occurrence backbone (footnotes excluded; ADR)
 *   • gold ring  = luminaries (top-8 by factor)
 *   • hover      = pause the drift (desktop only)
 *   • click node = open Netzwerke → Stammbaum on analytics.html
 *
 * Figure/edge data is EMBEDDED below (no runtime fetch) and regenerated from
 * data/agw_corpus.json + data/agw_proximity_body.json by tools/hero_data.py —
 * never hand-edit the block between the @@HERO-DATA@@ markers.
 *
 * Self-mounts: finds .hero, injects a background <canvas> + scrim behind
 * .hero-inner. Pure vanilla JS, no dependencies. The "Was uns beschäftigt"
 * rotator reads recent Jahrestagung themes from the global ARCHIVE and follows
 * the DE/EN language toggle. Respects prefers-reduced-motion.
 */
(function () {
  'use strict';

  /* @@HERO-DATA:BEGIN — generated by tools/hero_data.py, do not edit by hand @@ */
  var FIGS = [
    {"n": "Schumpeter", "b": 1883, "d": 1950, "c": "#edc948", "p": 1, "f": 100.0, "id": "schumpeter-joseph-alois", "sid": "schumpeter"},
    {"n": "Hayek", "b": 1899, "d": 1992, "c": "#3FB0A3", "p": 1, "f": 92.4, "id": "hayek-friedrich-august", "sid": "hayek"},
    {"n": "Smith", "b": 1723, "d": 1790, "c": "#C2A06B", "p": 1, "f": 89.2, "id": "smith-adam", "sid": "smith"},
    {"n": "Keynes", "b": 1883, "d": 1946, "c": "#6BB58C", "p": 1, "f": 88.8, "id": "keynes-john-maynard", "sid": "keynes"},
    {"n": "Mill", "b": 1806, "d": 1873, "c": "#C2A06B", "p": 1, "f": 86.5, "id": "mill-john-stuart", "sid": "mill"},
    {"n": "Wicksell", "b": 1851, "d": 1926, "c": "#9AA6D0", "p": 1, "f": 82.4, "id": "wicksell-knut", "sid": "wicksell"},
    {"n": "Röpke", "b": 1899, "d": 1966, "c": "#D6A24A", "p": 1, "f": 81.3, "id": "ropke-wilhelm", "sid": "roepke"},
    {"n": "Eucken", "b": 1891, "d": 1950, "c": "#D6A24A", "p": 1, "f": 77.8, "id": "eucken-walter", "sid": "eucken"},
    {"n": "Samuelson", "b": 1915, "d": 2009, "c": "#9AA6D0", "p": 1, "f": 77.5, "id": "samuelson-paul-anthony", "sid": "samuelson"},
    {"n": "Weber", "b": 1864, "d": 1920, "c": "#6E8FCB", "p": 1, "f": 76.1, "id": "weber-max", "sid": "mweber"},
    {"n": "Sraffa", "b": 1898, "d": 1983, "c": "#7fb3c9", "p": 0, "f": 76.1, "id": "sraffa-piero", "sid": null},
    {"n": "Marshall", "b": 1842, "d": 1924, "c": "#9AA6D0", "p": 0, "f": 75.1, "id": "marshall-alfred", "sid": "marshall"},
    {"n": "Schneider", "b": 1900, "d": 1970, "c": "#9AA6D0", "p": 0, "f": 74.9, "id": "schneider-erich", "sid": null},
    {"n": "Marx", "b": 1818, "d": 1883, "c": "#b07aa1", "p": 0, "f": 74.6, "id": "marx-karl", "sid": "marx"},
    {"n": "Krugman", "b": 1953, "d": null, "c": "#8cd17d", "p": 0, "f": 74.2, "id": "krugman-paul-robin", "sid": null},
    {"n": "Menger", "b": 1840, "d": 1921, "c": "#3FB0A3", "p": 0, "f": 74.1, "id": "menger-carl", "sid": "menger"},
    {"n": "Patinkin", "b": 1922, "d": 1995, "c": "#6BB58C", "p": 0, "f": 71.5, "id": "patinkin-don", "sid": null},
    {"n": "Ricardo", "b": 1772, "d": 1823, "c": "#C2A06B", "p": 0, "f": 71.2, "id": "ricardo-david", "sid": "ricardo"},
    {"n": "Sombart", "b": 1863, "d": 1941, "c": "#6E8FCB", "p": 0, "f": 70.8, "id": "sombart-werner", "sid": "sombart"},
    {"n": "Friedman", "b": 1912, "d": 2006, "c": "#9AA6D0", "p": 0, "f": 70.7, "id": "friedman-milton", "sid": "friedman"},
    {"n": "Hildebrand", "b": 1812, "d": 1878, "c": "#6E8FCB", "p": 0, "f": 70.6, "id": "hildebrand-bruno", "sid": "hildebrand"},
    {"n": "Blaug", "b": 1927, "d": 2011, "c": "#bab0ac", "p": 0, "f": 69.1, "id": "blaug-mark", "sid": null},
    {"n": "Böhm-Bawerk", "b": 1851, "d": 1914, "c": "#3FB0A3", "p": 0, "f": 66.6, "id": "bohm-bawerk-eugen", "sid": "boehm"},
    {"n": "Myrdal", "b": 1898, "d": 1987, "c": "#e79ab0", "p": 0, "f": 65.6, "id": "myrdal-gunnar", "sid": "myrdal"},
    {"n": "Roscher", "b": 1817, "d": 1894, "c": "#6E8FCB", "p": 0, "f": 65.5, "id": "roscher-wilhelm-georg-friedrich", "sid": "roscher"},
    {"n": "Neisser", "b": 1895, "d": 1975, "c": "#3FB0A3", "p": 0, "f": 64.6, "id": "neisser-hans-philip", "sid": null},
    {"n": "Häuser", "b": 1920, "d": 2002, "c": "#bab0ac", "p": 0, "f": 63.8, "id": "hauser-karl", "sid": null},
    {"n": "Lowe", "b": 1893, "d": 1995, "c": "#e79ab0", "p": 0, "f": 63.7, "id": "lowe-adolph", "sid": null},
    {"n": "Salin", "b": 1892, "d": 1974, "c": "#6E8FCB", "p": 0, "f": 63.5, "id": "salin-edgar", "sid": null},
    {"n": "Neumark", "b": 1900, "d": 1991, "c": "#8892A6", "p": 0, "f": 63.0, "id": "neumark-fritz", "sid": null},
    {"n": "Mises", "b": 1881, "d": 1973, "c": "#3FB0A3", "p": 0, "f": 62.9, "id": "mises-ludwig", "sid": "mises"},
    {"n": "Lösch", "b": 1906, "d": 1945, "c": "#8cd17d", "p": 0, "f": 62.6, "id": "losch-august", "sid": "loesch"},
    {"n": "Leijonhufvud", "b": 1933, "d": 2022, "c": "#6BB58C", "p": 0, "f": 61.5, "id": "leijonhufvud-axel", "sid": null},
    {"n": "Hicks", "b": 1904, "d": 1989, "c": "#9AA6D0", "p": 0, "f": 60.8, "id": "hicks-john-richard", "sid": "hicks"}
  ];
  var EDGES = [[9,18,1.0], [0,31,0.932], [1,30,0.93], [0,3,0.883], [2,17,0.883], [18,28,0.883], [2,13,0.861], [1,3,0.833], [0,18,0.819], [0,13,0.815], [3,7,0.789], [13,18,0.784], [0,1,0.773], [9,28,0.773], [13,17,0.773], [10,13,0.761], [7,31,0.742], [0,9,0.735], [0,22,0.728], [6,7,0.689], [12,26,0.689], [20,24,0.689], [3,12,0.68], [0,12,0.68], [11,17,0.671], [13,22,0.671], [3,25,0.671], [9,31,0.652], [6,12,0.641], [3,19,0.641], [1,27,0.641], [14,23,0.63], [3,5,0.619], [25,27,0.619], [5,22,0.606], [0,5,0.593], [3,6,0.593], [5,23,0.593], [8,33,0.58], [3,10,0.58], [1,25,0.58], [13,33,0.58], [0,2,0.565], [4,17,0.565], [9,24,0.565], [2,4,0.549], [8,12,0.549], [15,22,0.549], [0,30,0.549], [4,13,0.532], [10,11,0.532], [3,11,0.532], [2,24,0.513], [1,15,0.493], [0,15,0.47], [0,27,0.47], [24,28,0.47], [1,33,0.47], [1,19,0.445], [12,19,0.445], [26,29,0.445], [6,30,0.445], [5,8,0.416], [11,14,0.416], [3,16,0.416], [21,31,0.383], [2,20,0.297], [17,21,0.297], [2,23,0.297], [0,26,0.297], [9,14,0.235], [16,32,0.235], [15,20,0.235], [9,21,0.235], [2,29,0.235], [3,29,0.235], [5,32,0.235]];
  /* @@HERO-DATA:END@@ */

  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion:reduce)').matches;
  var canHover = window.matchMedia && window.matchMedia('(hover:hover) and (pointer:fine)').matches;
  var GOLD = '#E8C674';                    // luminary ring — a brighter gold than any school hue

  function hexa(hex, a) {
    var n = hex.replace('#', '');
    return 'rgba(' + parseInt(n.substr(0,2),16) + ',' + parseInt(n.substr(2,2),16) + ',' + parseInt(n.substr(4,2),16) + ',' + a + ')';
  }
  function dates(f){ if(f.b && f.d) return f.b + '\u2013' + f.d; if(f.b) return f.b + '\u2013'; return ''; }

  function init() {
    var hero = document.querySelector('.hero');
    if (!hero) return;                                            // guard
    if (document.getElementById('hero-network-canvas')) return;   // idempotent

    var cv = document.createElement('canvas');
    cv.id = 'hero-network-canvas';
    cv.setAttribute('aria-hidden', 'true');
    cv.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;z-index:0;' +
      'pointer-events:' + (canHover ? 'auto' : 'none') + ';';
    var scrim = document.createElement('div');
    scrim.setAttribute('aria-hidden', 'true');
    scrim.style.cssText = 'position:absolute;inset:0;z-index:1;pointer-events:none;' +
      'background:radial-gradient(115% 105% at 12% 42%, rgba(18,40,82,.55) 0%, rgba(18,40,82,.12) 48%, rgba(18,40,82,0) 70%),' +
      'linear-gradient(180deg, rgba(18,40,82,.10), rgba(18,40,82,.30));';
    hero.insertBefore(scrim, hero.firstChild);
    hero.insertBefore(cv, hero.firstChild);
    var inner = hero.querySelector('.hero-inner');
    if (inner) { inner.style.position = 'relative'; inner.style.zIndex = '2'; }

    var ctx = cv.getContext('2d');
    var W = 0, H = 0, DPR = Math.min(window.devicePixelRatio || 1, 2), raf = null, nodes = [];
    var t = 0, paused = false, hoverIdx = -1, neigh = [];

    // factor → radius mapping (a render tunable, not baked into the data)
    var fs = FIGS.map(function (f) { return f.f; });
    var FMIN = Math.min.apply(null, fs), FMAX = Math.max.apply(null, fs);
    function radius(f) {
      var span = (FMAX - FMIN) || 1;
      var r = 2.4 + ((f.f - FMIN) / span) * (6.6 - 2.4);
      return f.p ? r + 0.8 : r;
    }

    // adjacency (for hover neighbour highlighting)
    var ADJ = FIGS.map(function () { return []; });
    EDGES.forEach(function (e) { ADJ[e[0]].push(e[1]); ADJ[e[1]].push(e[0]); });

    function layout() {
      // light Fruchterman–Reingold pass so the real backbone reads as structure
      var wide = W > 860;
      var mL = wide ? W * 0.42 : W * 0.06;   // reserve the left for the hero text on desktop
      var mR = W * 0.05, mT = H * 0.08, mB = H * 0.08;
      var iw = W - mL - mR, ih = H - mT - mB;
      var k = Math.sqrt((iw * ih) / FIGS.length) * 0.55, cx = mL + iw / 2, cy = H / 2;
      var pos = FIGS.map(function () { return { x: mL + Math.random() * iw, y: mT + Math.random() * ih }; });
      var ITER = 260;
      for (var it = 0; it < ITER; it++) {
        var disp = pos.map(function () { return { x: 0, y: 0 }; });
        for (var i = 0; i < pos.length; i++) for (var j = i + 1; j < pos.length; j++) {
          var dx = pos[i].x - pos[j].x, dy = pos[i].y - pos[j].y, d = Math.hypot(dx, dy) || 0.01;
          var rep = (k * k) / d;
          var ux = dx / d, uy = dy / d;
          disp[i].x += ux * rep; disp[i].y += uy * rep;
          disp[j].x -= ux * rep; disp[j].y -= uy * rep;
        }
        EDGES.forEach(function (e) {
          var a = pos[e[0]], b = pos[e[1]];
          var dx = a.x - b.x, dy = a.y - b.y, d = Math.hypot(dx, dy) || 0.01;
          var att = (d * d) / k * (0.4 + 0.6 * e[2]);
          var ux = dx / d, uy = dy / d;
          disp[e[0]].x -= ux * att; disp[e[0]].y -= uy * att;
          disp[e[1]].x += ux * att; disp[e[1]].y += uy * att;
        });
        var temp = (k * 0.28) * (1 - it / ITER);
        for (var m = 0; m < pos.length; m++) {
          disp[m].x += (cx - pos[m].x) * 0.02; disp[m].y += (cy - pos[m].y) * 0.02;
          var dl = Math.hypot(disp[m].x, disp[m].y) || 0.01, lim = Math.min(dl, temp);
          pos[m].x += (disp[m].x / dl) * lim; pos[m].y += (disp[m].y / dl) * lim;
          pos[m].x = Math.max(mL, Math.min(W - mR, pos[m].x));
          pos[m].y = Math.max(mT, Math.min(H - mB, pos[m].y));
        }
      }
      return pos;
    }

    function make() {
      var pos = layout();
      nodes = FIGS.map(function (f, i) {
        return { i: i, name: f.n, sid: f.sid, dt: dates(f), prom: !!f.p, col: f.c, id: f.id,
          r: radius(f), bx: pos[i].x, by: pos[i].y, x: pos[i].x, y: pos[i].y,
          ph: Math.random() * 6.2832 };
      });
    }
    function size() {
      W = hero.clientWidth; H = hero.clientHeight;
      cv.width = W * DPR; cv.height = H * DPR; ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
      make();
    }

    function label(p, bright) {
      ctx.textBaseline = 'middle';
      var nameFont = p.prom ? "500 13px 'EB Garamond', serif" : "400 10px 'Source Sans 3', sans-serif";
      var dtFont   = p.prom ? "400 11px 'EB Garamond', serif" : "400 9px 'Source Sans 3', sans-serif";
      ctx.font = nameFont; var nw = ctx.measureText(p.name).width;
      ctx.font = dtFont;   var dw = p.dt ? ctx.measureText('  ' + p.dt).width : 0;
      var pad = p.r + 5, total = nw + dw;
      var lx = (p.x + pad + total > W - 6) ? p.x - pad - total : p.x + pad;
      var aName = p.prom ? 0.92 : 0.46, aDt = p.prom ? 0.55 : 0.3;
      if (bright) { aName = Math.min(1, aName + 0.35); aDt = Math.min(0.85, aDt + 0.35); }
      ctx.font = nameFont;
      ctx.fillStyle = 'rgba(255,255,255,' + aName + ')';
      ctx.fillText(p.name, lx, p.y);
      if (p.dt) { ctx.font = dtFont;
        ctx.fillStyle = 'rgba(210,222,242,' + aDt + ')';
        ctx.fillText('  ' + p.dt, lx + nw, p.y); }
    }

    function draw() {
      ctx.clearRect(0, 0, W, H);
      var focus = hoverIdx >= 0;
      // edges (real backbone)
      for (var e = 0; e < EDGES.length; e++) {
        var a = nodes[EDGES[e][0]], b = nodes[EDGES[e][1]], w = EDGES[e][2];
        var on = focus && (EDGES[e][0] === hoverIdx || EDGES[e][1] === hoverIdx);
        var al = (0.09 + 0.30 * w) * (focus ? (on ? 1.7 : 0.35) : 1);
        ctx.strokeStyle = on ? hexa(GOLD, Math.min(0.8, 0.4 + 0.5 * w)) : 'rgba(120,145,195,' + Math.min(0.6, al).toFixed(3) + ')';
        ctx.lineWidth = (0.6 + 1.3 * w) * (on ? 1.6 : 1);
        ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
      }
      // nodes
      for (var k = 0; k < nodes.length; k++) {
        var p = nodes[k];
        var dim = focus && k !== hoverIdx && neigh.indexOf(k) < 0;
        var fa = dim ? 0.35 : 1;
        if (p.prom) {
          ctx.save(); ctx.shadowColor = hexa(p.col, 0.5 * fa); ctx.shadowBlur = 9;
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, 6.2832); ctx.fillStyle = hexa(p.col, 0.98 * fa); ctx.fill(); ctx.restore();
          // gold luminary ring (with its own glow so it reads on gold-ish nodes)
          ctx.save(); ctx.shadowColor = hexa(GOLD, 0.55 * fa); ctx.shadowBlur = (k === hoverIdx) ? 12 : 6;
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r + 3.5, 0, 6.2832);
          ctx.strokeStyle = hexa(GOLD, (k === hoverIdx ? 0.95 : 0.7) * fa); ctx.lineWidth = 1.4; ctx.stroke(); ctx.restore();
        } else {
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, 6.2832); ctx.fillStyle = hexa(p.col, 0.9 * fa); ctx.fill();
          if (k === hoverIdx) { ctx.beginPath(); ctx.arc(p.x, p.y, p.r + 3, 0, 6.2832);
            ctx.strokeStyle = hexa(GOLD, 0.85); ctx.lineWidth = 1.2; ctx.stroke(); }
        }
        var bright = (k === hoverIdx) || (focus && neigh.indexOf(k) >= 0);
        if (!dim || p.prom) label(p, bright);
      }
    }

    function step(dt) {
      t += dt;
      for (var k = 0; k < nodes.length; k++) {
        var p = nodes[k];
        p.x = p.bx + Math.cos(t * 0.0016 + p.ph) * 4.0;
        p.y = p.by + Math.sin(t * 0.0014 + p.ph) * 4.0;
      }
    }
    var last = 0;
    function loop(ts) {
      var dt = last ? (ts - last) : 16; last = ts;
      if (!paused) step(dt);
      draw();
      raf = requestAnimationFrame(loop);
    }
    function start() { if (raf) cancelAnimationFrame(raf); last = 0; if (reduce) { draw(); return; } raf = requestAnimationFrame(loop); }

    // ── hover-to-pause + click → Stammbaum (desktop only) ──
    function pick(ev) {
      var rect = cv.getBoundingClientRect();
      var mx = ev.clientX - rect.left, my = ev.clientY - rect.top, best = -1, bd = 1e9;
      for (var k = 0; k < nodes.length; k++) {
        var d = Math.hypot(nodes[k].x - mx, nodes[k].y - my);
        if (d < nodes[k].r + 9 && d < bd) { bd = d; best = k; }
      }
      return best;
    }
    if (canHover) {
      cv.addEventListener('mousemove', function (ev) {
        paused = true;
        var h = pick(ev);
        if (h !== hoverIdx) { hoverIdx = h; neigh = h >= 0 ? ADJ[h] : []; }
        cv.style.cursor = h >= 0 ? 'pointer' : 'default';
        if (reduce) draw();
      });
      cv.addEventListener('mouseleave', function () {
        paused = false; hoverIdx = -1; neigh = []; cv.style.cursor = 'default'; if (reduce) draw();
      });
      cv.addEventListener('click', function (ev) {
        var h = pick(ev);
        if (h < 0) return;
        var key = nodes[h].sid || nodes[h].name;   // sid = exact Stammbaum id; name = graceful fallback
        window.location.href = 'analytics.html#stammbaum=' + encodeURIComponent(key);
      });
    }

    window.addEventListener('resize', function () { size(); start(); });
    size(); start();
    if (document.fonts && document.fonts.ready) { document.fonts.ready.then(function () { if (reduce) draw(); }); }

    initRotator();
  }

  // ── "Was uns beschäftigt" rotator — recent Jahrestagung themes from ARCHIVE ──
  function initRotator() {
    var el = document.getElementById('hero-rot-theme');
    if (!el) return;
    if (typeof ARCHIVE === 'undefined') return;
    var reduceR = window.matchMedia && window.matchMedia('(prefers-reduced-motion:reduce)').matches;
    function lang() { return (window.AGW && window.AGW.getLang) ? window.AGW.getLang() : 'de'; }
    function themes() {
      var de = lang() !== 'en';
      return ARCHIVE.filter(function (c) { return c.theme; })
        .slice().sort(function (a, b) { return (b.year || 0) - (a.year || 0); })
        .slice(0, 6)
        .map(function (c) { return (de ? c.theme : (c.theme_en || c.theme)) + ' (' + c.year + ')'; });
    }
    var list = themes(), ti = 0;
    function show() { el.textContent = list[ti] || ''; }
    show();
    window.addEventListener('agw-lang-change', function () { list = themes(); if (ti >= list.length) ti = 0; show(); });
    if (!reduceR && list.length > 1) {
      setInterval(function () { el.style.opacity = 0;
        setTimeout(function () { ti = (ti + 1) % list.length; show(); el.style.opacity = 1; }, 500);
      }, 3800);
    }
  }

  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', init); }
  else { init(); }
})();
