/* agw_data.js — Shared data arrays for the AGW site
 * ─────────────────────────────────────────────────────────────
 * Loaded by every page that needs them. Each constant is also
 * exposed on window.AGW_DATA for explicit access. Originally
 * inline in index.html; extracted in the multi-page migration.
 */

const CHAIRS = [
  { name:'Fritz Neumark', inst:'Goethe-Universität Frankfurt', start:1980, end:1982, past:true },
  { name:'Harald Scherf', inst:'Universität Hamburg', start:1982, end:1990, past:true },
  { name:'Bertram Schefold', inst:'Goethe-Universität Frankfurt', start:1990, end:1992, past:true },
  { name:'Heinz Rieter', inst:'Universität Hamburg', start:1992, end:1996, past:true },
  { name:'Erich Streißler', inst:'Universität Wien', start:1996, end:2000, past:true },
  { name:'Christian Scheer', inst:'Universität Hamburg', start:2000, end:2004, past:true },
  { name:'Harald Hagemann', inst:'Universität Hohenheim', start:2004, end:2008, past:true },
  { name:'Heinz D. Kurz', inst:'Karl-Franzens-Universität Graz', start:2008, end:2012, past:true },
  { name:'Hans-Michael Trautwein', inst:'Carl von Ossietzky Universität Oldenburg', start:2012, end:2016, past:true },
  { name:'Volker Caspari', inst:'Goethe-Universität Frankfurt', start:2016, end:2019, past:true },
  { name:'Peter Spahn', inst:'Universität Hohenheim', start:2019, end:2022, past:true },
  { name:'Rainer Klump', inst:'Goethe-Universität Frankfurt', start:2023, end:null, past:false },
];

const MEMBERS = [
  { name:'Elisabeth Allgoewer', title:'Prof. Dr.', inst:'Universität Hamburg', city:'Hamburg', country:'DE', emeritus:false, role:'', focus_de:'Geldtheorie, Makroökonomik, Geschichte der Ökonomik', focus_en:'Monetary theory, macroeconomics, history of economics' },
  { name:'Ingo Barens', title:'Prof. em. Dr.', inst:'TU Darmstadt', city:'Darmstadt', country:'DE', emeritus:true, role:'', focus_de:'Keynesianismus, Beschäftigungstheorie', focus_en:'Keynesianism, employment theory' },
  { name:'Reinhard Blomert', title:'Dr. habil.', inst:'Wissenschaftszentrum Berlin (WZB)', city:'Berlin', country:'DE', emeritus:false, role:'', focus_de:'Wissenssoziologie, Geschichte der Wirtschaftswissenschaften', focus_en:'Sociology of knowledge, history of economics' },
  { name:'David Bieri', title:'Prof. Dr.', inst:'Virginia Tech, Blacksburg', city:'Blacksburg', country:'US', emeritus:false, role:'host2026', focus_de:'Geschichte der Finanzmarkttheorie, Urban Economics', focus_en:'History of financial theory, urban economics' },
  { name:'Eduard Braun', title:'PD Dr.', inst:'TU Clausthal', city:'Clausthal', country:'DE', emeritus:false, role:'', focus_de:'Österreichische Schule, Kapitaltheorie', focus_en:'Austrian School, capital theory' },
  { name:'Volker Caspari', title:'Prof. em. Dr.', inst:'Goethe-Universität Frankfurt/Main', city:'Frankfurt', country:'DE', emeritus:true, role:'', focus_de:'Sraffa, Verteilungstheorie, Geschichte der ökonomischen Analyse', focus_en:'Sraffa, distribution theory, history of economic analysis' },
  { name:'Günther Chaloupek', title:'Dr.', inst:'Kammer für Arbeiter und Angestellte, Wien', city:'Wien', country:'AT', emeritus:false, role:'', focus_de:'Österreichische Wirtschaftsgeschichte, Arbeiterbewegung', focus_en:'Austrian economic history, labour movement' },
  { name:'Kurt Dopfer', title:'Prof. em. Dr.', inst:'Universität St. Gallen', city:'St. Gallen', country:'CH', emeritus:true, role:'', focus_de:'Evolutionäre Ökonomik, Rationalität', focus_en:'Evolutionary economics, rationality' },
  { name:'Alexander Ebner', title:'Prof. Dr.', inst:'Goethe-Universität Frankfurt a. M.', city:'Frankfurt', country:'DE', emeritus:false, role:'', focus_de:'Schumpeter, Evolutionsökonomik, Institutionenökonomik', focus_en:'Schumpeter, evolutionary economics, institutional economics' },
  { name:'Dirk Ehnts', title:'Dr.', inst:'TU Chemnitz', city:'Chemnitz', country:'DE', emeritus:false, role:'', focus_de:'Moderne Geldtheorie (MMT), Post-Keynesianismus', focus_en:'Modern Monetary Theory (MMT), Post-Keynesianism' },
  { name:'Svenja Flechtner', title:'Prof. Dr.', inst:'Universität Siegen', city:'Siegen', country:'DE', emeritus:false, role:'', focus_de:'Feministische Ökonomik, Heterodoxe Ökonomik', focus_en:'Feminist economics, heterodox economics' },
  { name:'Hans Frambach', title:'Prof. Dr.', inst:'Bergische Universität Wuppertal', city:'Wuppertal', country:'DE', emeritus:false, role:'', focus_de:'Geschichte des ökonomischen Denkens, Wohlfahrtstheorie', focus_en:'History of economic thought, welfare theory' },
  { name:'Christian Gehrke', title:'Prof. Dr.', inst:'Karl-Franzens-Universität Graz', city:'Graz', country:'AT', emeritus:false, role:'', focus_de:'Sraffa, klassische politische Ökonomie', focus_en:'Sraffa, classical political economy' },
  { name:'Nils Goldschmidt', title:'Prof. Dr.', inst:'Universität Siegen', city:'Siegen', country:'DE', emeritus:false, role:'', focus_de:'Ordoliberalismus, soziale Marktwirtschaft', focus_en:'Ordoliberalism, social market economy' },
  { name:'Jan Greitens', title:'Prof. Dr.', inst:'DHBW Mosbach', city:'Mosbach', country:'DE', emeritus:false, role:'', focus_de:'Geschichte der Geldtheorie', focus_en:'History of monetary theory' },
  { name:'Harald Hagemann', title:'Prof. em. Dr.', inst:'Universität Hohenheim', city:'Hohenheim', country:'DE', emeritus:true, role:'', focus_de:'Konjunkturtheorie, Geschichte der Makroökonomik', focus_en:'Business cycle theory, history of macroeconomics' },
  { name:'Tetsushi Harada', title:'Prof. Dr.', inst:'Kwansei Gakuin University', city:'Nishinomiya', country:'JP', emeritus:false, role:'', focus_de:'Rezeption deutschsprachiger Ökonomik in Japan', focus_en:'Reception of German-language economics in Japan' },
  { name:'Jochen Hartwig', title:'Prof. Dr.', inst:'TU Chemnitz', city:'Chemnitz', country:'DE', emeritus:false, role:'', focus_de:'Post-Keynesianismus, Verteilungstheorie', focus_en:'Post-Keynesianism, distribution theory' },
  { name:'Jan-Otmar Hesse', title:'Prof. Dr.', inst:'Universität Bayreuth', city:'Bayreuth', country:'DE', emeritus:false, role:'', focus_de:'Wirtschaftsgeschichte, Geschichte des Vereins für Socialpolitik', focus_en:'Economic history, history of the VfS' },
  { name:'Karen Horn', title:'Prof. Dr.', inst:'Universität Erfurt', city:'Erfurt', country:'DE', emeritus:false, role:'', focus_de:'Adam Smith, Geschichte des Liberalismus', focus_en:'Adam Smith, history of liberalism' },
  { name:'Hauke Janssen', title:'Dr.', inst:'(unabhängig)', city:'–', country:'DE', emeritus:false, role:'', focus_de:'Geschichte der Wirtschaftswissenschaften im Nationalsozialismus', focus_en:'History of economics under National Socialism' },
  { name:'Hansjörg Klausinger', title:'Prof. em. Dr.', inst:'Wirtschaftsuniversität Wien', city:'Wien', country:'AT', emeritus:true, role:'', focus_de:'Österreichische Schule, Hayek, Konjunkturtheorie', focus_en:'Austrian School, Hayek, business cycle theory' },
  { name:'Rainer Klump', title:'Prof. Dr.', inst:'Goethe-Universität Frankfurt', city:'Frankfurt', country:'DE', emeritus:false, role:'chair', focus_de:'Wachstumstheorie, Institutionenökonomik, Dogmengeschichte', focus_en:'Growth theory, institutional economics, history of doctrines' },
  { name:'Stefan Kolev', title:'Prof. Dr.', inst:'Westfälische Hochschule Zwickau', city:'Zwickau', country:'DE', emeritus:false, role:'', focus_de:'Ordoliberalismus, Hayek, Mont Pèlerin Society', focus_en:'Ordoliberalism, Hayek, Mont Pèlerin Society' },
  { name:'Hagen Krämer', title:'Prof. Dr.', inst:'Hochschule Karlsruhe', city:'Karlsruhe', country:'DE', emeritus:false, role:'', focus_de:'Einkommensverteilung, Post-Keynesianismus', focus_en:'Income distribution, Post-Keynesianism' },
  { name:'Heinz D. Kurz', title:'Prof. em. Dr.', inst:'Karl-Franzens-Universität Graz', city:'Graz', country:'AT', emeritus:true, role:'', focus_de:'Sraffa, klassische politische Ökonomie, Kapitaltheorie', focus_en:'Sraffa, classical political economy, capital theory' },
  { name:'Oliver Landmann', title:'Prof. em. Dr.', inst:'Universität Freiburg', city:'Freiburg', country:'DE', emeritus:true, role:'', focus_de:'Wachstumstheorie, internationale Makroökonomik', focus_en:'Growth theory, international macroeconomics' },
  { name:'Hans-Walter Lorenz', title:'Prof. Dr. em.', inst:'Wirtschaftswissenschaftliche Fakultät', city:'–', country:'DE', emeritus:true, role:'', focus_de:'Nichtlineare Dynamik, Konjunkturtheorie', focus_en:'Nonlinear dynamics, business cycle theory' },
  { name:'Karl Milford', title:'Prof. Dr.', inst:'Universität Wien', city:'Wien', country:'AT', emeritus:false, role:'', focus_de:'Wissenschaftstheorie, Popper, Geschichte der Methodologie', focus_en:'Philosophy of science, Popper, history of methodology' },
  { name:'Arash Molavi', title:'Dr.', inst:'Finanzministerium Berlin', city:'Berlin', country:'DE', emeritus:false, role:'', focus_de:'Evolutionsökonomik, Wettbewerbstheorie', focus_en:'Evolutionary economics, competition theory' },
  { name:'Helge Peukert', title:'Prof. Dr. Dr.', inst:'Universität Siegen', city:'Siegen', country:'DE', emeritus:false, role:'', focus_de:'Schumpeter, Geschichte der Konjunkturtheorie', focus_en:'Schumpeter, history of business cycle theory' },
  { name:'Birger Priddat', title:'Prof. em. Dr.', inst:'Universität Witten/Herdecke', city:'Witten', country:'DE', emeritus:true, role:'', focus_de:'Institutionenökonomik, Rhetorik der Ökonomik', focus_en:'Institutional economics, rhetoric of economics' },
  { name:'Heinz Rieter', title:'Prof. em. Dr.', inst:'Universität Hamburg', city:'Hamburg', country:'DE', emeritus:true, role:'', focus_de:'Geschichte der Wirtschaftswissenschaften, Methodologie', focus_en:'History of economics, methodology' },
  { name:'Philipp Robinson Rössner', title:'Prof. Dr.', inst:'University of Manchester', city:'Manchester', country:'UK', emeritus:false, role:'', focus_de:'Frühneuzeitliche Wirtschaftsgeschichte, monetäre Geschichte', focus_en:'Early modern economic history, monetary history' },
  { name:'Peter Rosner', title:'Prof. Dr.', inst:'Universität Wien', city:'Wien', country:'AT', emeritus:false, role:'', focus_de:'Geschichte der Beschäftigungstheorie', focus_en:'History of employment theory' },
  { name:'Christian Scheer', title:'Prof. em. Dr.', inst:'Universität Hamburg', city:'Hamburg', country:'DE', emeritus:true, role:'', focus_de:'Deutsche Finanzwissenschaft, Geschichte der Wirtschaftspolitik', focus_en:'German public finance, history of economic policy' },
  { name:'Bertram Schefold', title:'Prof. Dr. Drs. h.c.', inst:'Goethe-Universität Frankfurt', city:'Frankfurt', country:'DE', emeritus:false, role:'', focus_de:'Sraffa, klassische politische Ökonomie, Geschichte der VWL', focus_en:'Sraffa, classical political economy, history of economics' },
  { name:'Johannes Schmidt', title:'Prof. Dr.', inst:'Hochschule Karlsruhe', city:'Karlsruhe', country:'DE', emeritus:false, role:'', focus_de:'Beschäftigungstheorie, monetäre Ökonomik', focus_en:'Employment theory, monetary economics' },
  { name:'Peter Spahn', title:'Prof. em. Dr.', inst:'Universität Hohenheim', city:'Hohenheim', country:'DE', emeritus:true, role:'', focus_de:'Geschichte der Makroökonomik, monetäre Ökonomik', focus_en:'History of macroeconomics, monetary economics' },
  { name:'Richard Sturn', title:'Prof. Dr.', inst:'Universität Graz', city:'Graz', country:'AT', emeritus:false, role:'', focus_de:'Klassische politische Ökonomie, Wohlfahrtstheorie', focus_en:'Classical political economy, welfare theory' },
  { name:'Stephan Thomsen', title:'Prof. Dr.', inst:'Leibniz Universität Hannover', city:'Hannover', country:'DE', emeritus:false, role:'', focus_de:'Arbeitsmarktökonomik, politische Ökonomie', focus_en:'Labour economics, political economy' },
  { name:'Horst Todt', title:'Prof. em. Dr.', inst:'Universität Hamburg', city:'Hamburg', country:'DE', emeritus:true, role:'', focus_de:'Geschichte der Volkswirtschaftslehre', focus_en:'History of economics' },
  { name:'Hans-Michael Trautwein', title:'Prof. Dr.', inst:'Carl von Ossietzky Universität Oldenburg', city:'Oldenburg', country:'DE', emeritus:false, role:'', focus_de:'Makroökonomik, Geldtheorie, Geschichte der Makroökonomik', focus_en:'Macroeconomics, monetary theory, history of macroeconomics' },
  { name:'Helmut Wagner', title:'Prof. Dr.', inst:'FernUniversität Hagen', city:'Hagen', country:'DE', emeritus:false, role:'', focus_de:'Internationale Währungsökonomik, Makroökonomik', focus_en:'International monetary economics, macroeconomics' },
  { name:'Gerhard Wegner', title:'Prof. Dr.', inst:'Universität Erfurt', city:'Erfurt', country:'DE', emeritus:false, role:'', focus_de:'Hayeksche Evolutionstheorie, Ordnungsökonomik', focus_en:'Hayekian evolutionary theory, constitutional economics' },
  { name:'Carl Christian von Weizsäcker', title:'Prof. em. Dr.', inst:'Max-Planck-Institut, Bonn', city:'Bonn', country:'DE', emeritus:true, role:'', focus_de:'Kapitaltheorie, allgemeine Gleichgewichtstheorie', focus_en:'Capital theory, general equilibrium theory' },
  { name:'Michael Wohlgemuth', title:'Prof. Dr.', inst:'Universität Witten/Herdecke', city:'Witten', country:'DE', emeritus:false, role:'', focus_de:'Evolutionäre Ökonomik, Ordoliberalismus', focus_en:'Evolutionary economics, ordoliberalism' },
  { name:'Joachim Zweynert', title:'Prof. Dr.', inst:'Universität Witten/Herdecke', city:'Witten', country:'DE', emeritus:false, role:'', focus_de:'Geschichte der Wirtschaftswissenschaften in Osteuropa', focus_en:'History of economics in Eastern Europe' },
];

const ARCHIVE = [
  { nr:46, year:2026, dates:'25.–27. Juni 2026', country:'CH', loc_de:'Riva San Vitale, Tessin', loc_en:'Riva San Vitale, Ticino', venue:'Virginia Tech Steger Center, Villa Maderni', theme:'Zukunftsperspektiven der Theoriegeschichte: Methoden, Themen, Kontroversen', theme_en:'Future Perspectives in the History of Economic Thought: Methods, Topics, Controversies', vol:null, papers:[
    { author:'Hans-Michael Trautwein · Richard Sturn', title:'Der Stand und die Zukunft der theoriegeschichtlichen Forschung', inst:'Oldenburg · Graz' },
    { author:'Alexander Linsbichler', title:'Theoriegeschichte und Wissenschaftsphilosophie', inst:'Linz' },
    { author:'Gilles Campagnolo', title:'Inhalt und Grenzen der «philosophie économique»', inst:'Paris' },
    { author:'Catherine Herfeld', title:'Worum geht es eigentlich? Rationale Entscheidungstheorie', inst:'Hannover' },
    { author:'Hermann Rauchenschwandtner', title:'Wirtschaft und Leben: Friedrich von Gottl-Ottlilienfeld', inst:'Salzburg' },
    { author:'Anselm Küsters', title:'Quantitative Textanalyse transnationaler Verbindungen in der ordoliberalen Tradition', inst:'Berlin/Stuttgart' },
    { author:'Karl Milford', title:'Theorien des wissenschaftlichen Fortschritts und Geschichtsschreibung', inst:'Wien' },
    { author:'Andreas Lingg', title:'Geschichte schreiben. Die Vergangenheit der ökonomischen Moderne', inst:'Witten/Herdecke' },
    { author:'Andrea Franc', title:'Wie Geschichte des ökonomischen Denkens unterrichten?', inst:'Luzern' },
    { author:'Lachezar Grudev', title:'Geschichte der ökonomischen Analyse – wozu?', inst:'Chemnitz' }
  ] },
  { nr:45, year:2025, dates:'9.–10. Mai 2025', country:'DE', loc_de:'Bayreuth', loc_en:'Bayreuth', venue:'Universität Bayreuth', theme:'Theoriegeschichte der Geoökonomik', theme_en:'History of Economic Thought on Geo-economics', vol:null, papers:[
    { author:'Julius Nipperdey', title:'Kameralismus und die globale Wirtschaft', inst:'Saarbrücken' },
    { author:'Richard Sturn', title:'Adam Smiths Geoökonomik: Zwischen Freihandelsideal und geopolitischem Realismus', inst:'Graz' },
    { author:'Birger Priddat', title:'Über den Handel. Kant und Fichte. Pro und Contra.', inst:'Witten/Herdecke' },
    { author:'Werner Plumpe', title:'Friedrich List', inst:'Frankfurt am Main' },
    { author:'Kiichiro Yagi', title:'Colonialism Studies in the Age of Japanese Empire: Inazo Nitobe, Tadao Yanaihara, and Marxists', inst:'Osaka' },
    { author:'Jan-Otmar Hesse', title:'Herbert Giersch und die Kieler Schule der Standorttheorie', inst:'Bayreuth' },
    { author:'Reinhard Schumacher · Svenja Flechtner · Matthias Störring', title:'Charlotte Leubuscher (1888–1961): Von der Sozialen Frage zur Pionierin der Entwicklungsökonomik', inst:'Siegen/Berlin' },
    { author:'Daniel Nientiedt', title:'Hayek zu Internationalem Föderalismus', inst:'Freiburg' }
  ] },
  { nr:44, year:2024, dates:'30. Mai – 1. Juni 2024', country:'DE', loc_de:'Fulda', loc_en:'Fulda', venue:'Stadtschloss Fulda, Marmorsaal', theme:'Frauen in der Geschichte der Wirtschaftswissenschaften', theme_en:'Women in the History of Economics', vol:null, papers:[
    { author:'Kerstin Dross-Krüpe', title:'Frauen und Wirtschaft in der römischen Antike', inst:'' },
    { author:'Charlotte Backerra', title:'Regierende Frauen in der frühen Neuzeit und ihre Wirtschaftskompetenz', inst:'' },
    { author:'Elisabeth Allgoewer', title:'Frauen im Verein für Socialpolitik', inst:'Hamburg' },
    { author:'Christian Kremser', title:'Beatrice Webb (1858–1943) als Ökonomin', inst:'' },
    { author:'Günther Chaloupek', title:'Helene Bauer (1871–1942) – bürgerliche und sozialistische Ökonomie', inst:'Wien' },
    { author:'Reinhard Schumacher · Svenja Flechtner · Matthias Störring', title:'Charlotte Leubuscher (1888–1961)', inst:'Siegen/Berlin' },
    { author:'Uwe Dathe · Daniel Nientiedt', title:'Edith Eucken (1896–1985)', inst:'' },
    { author:'Hans Frambach', title:'Cläre Tisch (1907–1941) – Leben und Werk', inst:'Wuppertal' },
    { author:'Harald Hagemann', title:'Fanny Ginor (1911–2007): Die Basler Nationalökonomie nach Israel getragen', inst:'Hohenheim' },
    { author:'Lachezar Grudev', title:'Vera Smith (1912–1976). Eine mutige Ökonomin im Spannungsfeld dreier Welten', inst:'Zwickau' },
    { author:'Bertram Schefold', title:'Joan Robinson (1903–1983) – eine persönliche Charakterisierung (Kamingespräch)', inst:'Frankfurt' }
  ] },
  { nr:43, year:2023, dates:'21.–23. Juni 2023', country:'UK', loc_de:'Edinburgh', loc_en:'Edinburgh', venue:'Panmure House / Queen Margaret University', theme:'Adam Smith @ 300', theme_en:'Adam Smith @ 300', vol:'XLII', papers:[
    { author:'Karen Horn', title:'Geschichte der Wirtschaftswissenschaften als interdisziplinäre Aufgabe: Ein Überblick über die jüngere Adam-Smith-Forschung', inst:'Erfurt' },
    { author:'Philipp Robinson Rössner', title:'Smith\'s Scotland. Contextualising the Wealth of Nations', inst:'Manchester' },
    { author:'Sabine Föllinger', title:'Antike Philosophie im Denken von Adam Smith', inst:'Marburg' },
    { author:'Reinhard Schumacher', title:'Die unterschiedlichen Ansichten Adam Smiths und David Humes über wirtschaftliche Entwicklung und zwischenstaatliche Kriege', inst:'Potsdam' },
    { author:'Ludwig Nellinger', title:'Methodik und Erkenntnisfortschritt: Adam Smith und Johann Heinrich von Thünen', inst:'Bonn' },
    { author:'Heinz D. Kurz', title:'Smith, Marx und Schumpeter über den Zivilisationsprozess. Ein Vergleich ihrer evolutorischen Ansätze', inst:'Graz' },
    { author:'Reinhard Blomert', title:'Adam Smith über Gentlemen, Geschäftsleute und innere Richter. Eine Rekonfiguration', inst:'Berlin' }
  ] },
  { nr:42, year:2022, dates:'16.–18. Juni 2022', country:'DE', loc_de:'Jena', loc_en:'Jena', venue:'Universität Jena', theme:'Zur Geschichte des Vereins für Socialpolitik', theme_en:'On the History of the Verein für Socialpolitik', vol:'XLI', papers:[
    { author:'Bertram Schefold', title:'Das sich wandelnde Selbstverständnis des VfS im Spiegel seiner Jahrestagungen, 1950–2000', inst:'Frankfurt' },
    { author:'Jan-Otmar Hesse', title:'Die wirtschaftshistorische Forschung im VfS', inst:'Bayreuth' },
    { author:'Elisabeth Allgoewer', title:'Frauen im Verein für Socialpolitik', inst:'Hamburg' },
    { author:'Alexander Ebner', title:'Schmollers Rolle im VfS', inst:'Frankfurt' },
    { author:'Erwin Dekker · Stefan Kolev', title:'Sozialpolitik in der Moderne – zwischen historischem Kontext und überzeitlichem Fixpunkt', inst:'Zwickau' },
    { author:'Uwe Dathe', title:'Eucken in Jena', inst:'Thüringer Univ.- u. Landesbibliothek' },
    { author:'Tetsushi Harada', title:'Die Selbstauflösung des Vereins für Socialpolitik und die Herausgabe der Werke Friedrich Lists', inst:'Nishinomiya' },
    { author:'Volker Caspari', title:'Evidenz, evidence und evidenzbasierte Wirtschaftspolitik – der empirical turn in der VWL', inst:'Frankfurt' }
  ] },
  { nr:41, year:2021, dates:'4.–5. Juni 2021', country:'INT', loc_de:'Online (Zoom)', loc_en:'Online (Zoom)', venue:'Zoom · Host: Goethe-Universität Frankfurt', theme:'Entwicklung der Konjunkturforschung im frühen 20. Jahrhundert', theme_en:'Development of Business Cycle Research in the Early 20th Century', vol:'XL', papers:[
    { author:'Dirk Ehnts', title:'Frederick Lavington über den Konjunkturzyklus', inst:'Chemnitz' },
    { author:'Jan Greitens', title:'Die Rezeption der Staatlichen Theorie des Geldes', inst:'Mosbach' },
    { author:'Stefan Kolev', title:'Ein Baltendeutscher bei den Preußen des Balkans – Oskar Anderson und das Sofioter Institut für Wirtschaftsforschung', inst:'Zwickau' },
    { author:'Laetitia Lenel', title:'Der Harvard Index of General Business Conditions und seine Rezeption in Europa', inst:'' },
    { author:'Oliver Landmann', title:'Zur Rezeption von Keynes in Deutschland während der Weltwirtschaftskrise', inst:'Freiburg' },
    { author:'Jochen Hartwig', title:'Die Genese von Patinkins Interpretation von Keynes\' Theorie der effektiven Nachfrage', inst:'Chemnitz' },
    { author:'Hansjörg Klausinger', title:'Das Österreichische Institut für Konjunkturforschung, 1927–1938', inst:'Wien' },
    { author:'David Bieri', title:'Zwischen Anschaulichkeit und Beobachtbarkeit – Der Streit um das Wesen der deutschsprachigen Konjunkturtheorie in der Zwischenkriegszeit', inst:'Virginia Tech' },
    { author:'Harald Hagemann', title:'Wie ist Konjunkturtheorie überhaupt möglich? Zur (In-)Kompatibilität von zyklischen Schwankungen und Gleichgewichtstheorie', inst:'Hohenheim' }
  ] },
  { nr:40, year:2019, dates:'6.–8. Juni 2019', country:'DE', loc_de:'Hamburg', loc_en:'Hamburg', venue:'Hamburg Center for Health Economics, Esplanade 36', theme:'Ökonomie und Evolution', theme_en:'Economics and Evolution', vol:'XXXVI', papers:[
    { author:'Kurt Dopfer', title:'Die Idee der Evolution in den Wirtschaftswissenschaften – Ein theoriegeschichtlicher Abriss', inst:'St. Gallen' },
    { author:'Hans-Walter Lorenz', title:'Darwinismus in der Ökonomie – Von Marx & Engels bis Nelson & Winter', inst:'' },
    { author:'Alexander Ebner', title:'Wirtschaftliche Entwicklung als evolutionärer Prozess? Kontinuität und Wandel des Evolutionsbegriffs bei Joseph Schumpeter', inst:'Frankfurt' },
    { author:'Arash Molavi', title:'Evolution und Wettbewerb – Marktselektionstheorie seit Alchian und Friedman', inst:'Berlin' },
    { author:'Helmut Wagner', title:'Evolution aus makroökonomischer Perspektive – Zur Erklärung von Übergangsprozessen', inst:'Hagen' },
    { author:'Gerhard Wegner', title:'Hayeks Theorie der Marktevolution als politische Theorie – eine kritische Würdigung', inst:'Erfurt' },
    { author:'Birger Priddat', title:'Über den Einfluss der Institutionenökonomie auf die Evolution von Handlungsmodellen', inst:'Witten/Herdecke' },
    { author:'Carl Christian von Weizsäcker', title:'Hegels Begründung des Marktprinzips in evolutorischer Absicht', inst:'Bonn' }
  ] },
  { nr:39, year:2018, dates:'23.–25. Mai 2018', country:'DE', loc_de:'Darmstadt', loc_en:'Darmstadt', venue:'Technische Universität Darmstadt', theme:'Kameralismus und Merkantilismus', theme_en:'Cameralism and Mercantilism', vol:'XXXIX', papers:[
    { author:'Peter Spahn', title:'Was war falsch am Merkantilismus?', inst:'Hohenheim' },
    { author:'Birger Priddat', title:'Homo imperfectabilis und die Vervollkommnung des Menschen durch Ordnung', inst:'Witten/Herdecke' },
    { author:'Toni Pierenkemper', title:'Frideridzianischer Kameralismus in Preußen 1740–1786', inst:'Köln' },
    { author:'Tetsushi Harada', title:'Justus Mösers wirtschaftliche Ideen und ihre Einordnung bei Roscher und in der Geschichte der deutschen Volkswirtschaftslehre', inst:'Nishinomiya' },
    { author:'Rainer Klump', title:'Von Seckendorff zu Moser: Finanz- und wirtschaftspolitische Herausforderungen und Reformpläne in Hessen-Darmstadt 1660–1780', inst:'Frankfurt' },
    { author:'Günther Chaloupek', title:'Der Mann ohne Vorurteil: Die Bedeutung von Joseph von Sonnenfels für Wirtschaftswissenschaft und Wirtschaftspolitik', inst:'Wien' },
    { author:'Erik S. Reinert', title:'Giovanni Botero (1540–1617) als gemeinsamer Ursprung von Kameralismus und Merkantilismus', inst:'Tallinn' },
    { author:'Eduard Braun', title:'Die Rolle des Merkantilismus bei der Trennung von Staat und Gesellschaft', inst:'Clausthal' }
  ] },
  { nr:38, year:2017, dates:'9.–11. Juni 2017', country:'DE', loc_de:'Siegen', loc_en:'Siegen', venue:'Campus Unteres Schloss, Universität Siegen', theme:'Einkommens- und Vermögensverteilung in historischer Perspektive', theme_en:'Income and Wealth Distribution in Historical Perspective', vol:'XXXVII', papers:[
    { author:'Hagen Krämer', title:'Funktionale und normative Aspekte von individuellem Reichtum in ökonomischen Theorien von der Klassik bis zur Moderne', inst:'Karlsruhe' },
    { author:'Bertram Schefold', title:'The Improbability of Reswitching, the Certainty of Wicksell-Effects and the Poverty of Production Functions', inst:'Frankfurt' },
    { author:'Jan-Otmar Hesse', title:'Thomas Pikettys Kapital im 21. Jahrhundert aus Sicht der Wirtschaftsgeschichte', inst:'Bayreuth' },
    { author:'Fritz Helmedag', title:'Profitrate, Zinssatz, Gewinn: Irrungen und Wirrungen', inst:'Chemnitz' },
    { author:'Karen Horn', title:'Arm und Reich im Werk von Adam Smith', inst:'Erfurt' },
    { author:'Stephan Thomsen', title:'Die Rolle von Computern und Informationstechnik für die Einkommens- und Vermögensverteilung', inst:'Hannover' },
    { author:'David Bieri', title:'Raum und Geld: Eine Neubewertung von August Löschs Theorie der Währung und ihre Bedeutung für regionalökonomische Verteilungsfragen', inst:'Virginia Tech' }
  ] },
  { nr:37, year:2016, dates:'9.–11. Juni 2016', country:'DE', loc_de:'Karlsruhe', loc_en:'Karlsruhe', venue:'Prinz-Max-Palais, Karlsruhe', theme:'Deflations- und Stagnationstheorien', theme_en:'Theories of Deflation and Stagnation', vol:null, papers:[
    { author:'Heinz D. Kurz', title:'Ein Gespenst geht um in Europa – das Gespenst säkularer Stagnation', inst:'Graz' },
    { author:'Peter Spahn', title:'Bevölkerungswachstum, Ersparnis, Zins und Stagnation', inst:'Hohenheim' },
    { author:'Harald Hagemann', title:'Die neue säkulare Stagnations-Hypothese: Summers after Hansen', inst:'Hohenheim' },
    { author:'Günther Chaloupek', title:'Spätkapitalismus als Stagnationstheorie – die deutsche Diskussion in den 1920er Jahren', inst:'Wien' },
    { author:'Hansjörg Klausinger', title:'Woher kommt und wie schädlich ist Deflation? Die österreichische Konjunkturtheorie zur Großen Depression', inst:'Wien' },
    { author:'Hans-Michael Trautwein', title:'Hans Neisser über strukturelle Deflation und persistente Arbeitslosigkeit', inst:'Oldenburg' },
    { author:'Ingo Barens', title:'Nicht-positive Zinsen – ein theoriegeschichtlicher Rückblick', inst:'Darmstadt' }
  ] },
  { nr:36, year:2015, dates:'4.–6. Juni 2015', country:'DE', loc_de:'Erfurt', loc_en:'Erfurt', venue:'Augustiner Kloster, Erfurt', theme:'Kontinuität und Wandel in der Institutionenökonomik', theme_en:'Continuity and Change in Institutional Economics', vol:null, papers:[
    { author:'Birger Priddat', title:'Taugt die Institutionenökonomik als moderne historische Methode?', inst:'Witten/Herdecke' },
    { author:'Rudolf Richter', title:'Ungewissheit der Zukunft in der Wirtschaftstheorie – Aus Sicht der Neuen Institutionenökonomik', inst:'Saarbrücken' },
    { author:'Joachim Zweynert', title:'Neueste Institutionenökonomik und neue Brücken zwischen Wirtschafts- und Sozialwissenschaften', inst:'Witten/Herdecke' },
    { author:'Gerhard Wegner', title:'Institutionenökonomische Narrative für die Entstehung des modernen Kapitalismus', inst:'Erfurt' },
    { author:'Alexander Ebner', title:'Out-Schmollering Schmoller? Die Renaissance kultureller Perspektiven in der Institutionenökonomik', inst:'Frankfurt' },
    { author:'Toni Pierenkemper', title:'Gregory King (1648–1712) als Pionier der empirischen Sozialwissenschaft', inst:'Münster' },
    { author:'Volker Caspari', title:'Warum Nationen scheitern: Daron Acemoglus Anwendung der Institutionenökonomik auf die Wachstums- und Entwicklungsforschung', inst:'Darmstadt' }
  ] },
  { nr:35, year:2014, dates:'15.–17. Mai 2014', country:'AT', loc_de:'Wien', loc_en:'Vienna', venue:'Diplomatische Akademie Wien', theme:'Macht oder ökonomisches Gesetz?', theme_en:'Political Control or Economic Law?', vol:'XXXV', papers:[
    { author:'Carl Christian von Weizsäcker', title:'Böhm-Bawerks temporale Kapitaltheorie: Ihre Modernisierung und Aktualität', inst:'Köln', discussant:'Korreferat: Bertram Schefold (Frankfurt)' },
    { author:'Bertram Schefold', title:'Korreferat zu Weizsäcker', inst:'Frankfurt' },
    { author:'Fritz Helmedag', title:'Böhm-Bawerks Kapitaltheorie im Lichte des Waldproblems: Eine Neubewertung', inst:'Chemnitz' },
    { author:'Jan-Otmar Hesse', title:'Die Debatte über die Produktionsumwege', inst:'Bielefeld' },
    { author:'Johannes Schmidt', title:'Böhm-Bawerk nach Stützel: Was bleibt von der Zinstheorie?', inst:'Karlsruhe' },
    { author:'Manfred Holler', title:'Zur Geschichte der Machtindizes in der Ökonomie', inst:'Hamburg' },
    { author:'Monika Poettinger', title:'Between History and Theory: Otto Neurath 1906–17', inst:'Mailand' },
    { author:'Christian Gehrke · Florian Brugger', title:'Preisinduzierter technischer Fortschritt in der ökonomischen Theoriengeschichte', inst:'Graz' },
    { author:'Peter Spahn', title:'Böhm-Bawerk und die Entstehung der Zinspolitik', inst:'Hohenheim' },
    { author:'Hauke Janssen', title:'Max Weber über Macht und ökonomisches Gesetz', inst:'Hamburg' },
    { author:'Gilles Campagnolo', title:'The Foundations of the Theory of Entrepreneurship in Austrian Economics? Menger and Böhm-Bawerk on the Entrepreneur', inst:'Aix-en-Provence' }
  ] },
  { nr:34, year:2013, dates:'7.–8. Juni 2013', country:'DE', loc_de:'Berlin', loc_en:'Berlin', venue:'Berlin-Brandenburgische Akademie der Wissenschaften', theme:'Neue Perspektiven auf die Politische Ökonomie von Karl Marx und Friedrich Engels / Die Marx-Engels-Gesamtausgabe (MEGA)', theme_en:'New Perspectives on the Political Economy of Marx and Engels: The Marx-Engels-Gesamtausgabe (MEGA)', vol:'XXXIV', papers:[
    { author:'Kiichiro Yagi', title:'The International Network around the MEGA project: from the 1920s to the 2010s', inst:'Osaka' },
    { author:'Regina Roth', title:'Über Differenzen zwischen den Engels\'schen Druckfassungen und den Marx\'schen Manuskripten des Kapital', inst:'Berlin-Brandenburgische Akademie' },
    { author:'Bertram Schefold', title:'Zwei maximale Profitraten, die Durchschnittsbildung und weitere Unterschiede zwischen Marx und Sraffa', inst:'Frankfurt' },
    { author:'Fritz Helmedag', title:'Über Kapital im Kapital: Einige elementare Überlegungen', inst:'Chemnitz' },
    { author:'Kenji Mori', title:'Karl Marx Krisenhefte von 1857-58 und die Produktionstheorie der Krise', inst:'Sendai' },
    { author:'Peter Rosner', title:'Über die Schwierigkeiten Ausbeutung in der Wirtschaftstheorie zu erfassen – von Rodbertus zu Marx', inst:'Wien' },
    { author:'Hagen Krämer', title:'Das klassische Konzept der unproduktiven Arbeit und seine Folgen für das moderne Verständnis von Dienstleistungen', inst:'Karlsruhe' },
    { author:'Birger Priddat', title:'Marx\' sparsames Konzept des Kommunismus', inst:'Witten/Herdecke' },
    { author:'Irwin Collier', title:'Marx in the Economics Curriculum: Harvard, Chicago and Columbia, 1900–1950', inst:'Berlin' }
  ] },
  { nr:33, year:2012, dates:'14.–16. Juni 2012', country:'DE', loc_de:'Marbach am Neckar', loc_en:'Marbach am Neckar', venue:'Deutsches Literaturarchiv Marbach', theme:'Die Zeit um den Ersten Weltkrieg als Krisenzeit der Nationalökonomen', theme_en:'The Era of the First World War as a Crisis Period for Economists', vol:'XXX', papers:[
    { author:'Bertram Schefold', title:'Goethe und die Anschauliche Theorie', inst:'Frankfurt' },
    { author:'Hauke Janssen', title:'Sozialpolitik, Wertlehre, Konjunkturforschung – Die Krise in der deutschen Nationalökonomie zur Zeit um den Ersten Weltkrieg', inst:'Hamburg' },
    { author:'Erik Grimmer-Solem', title:'Geopolitik und Staatswissenschaft im Ersten Weltkrieg', inst:'Middletown' },
    { author:'Hansjörg Klausinger', title:'Die Krise der Nationalökonomie an der Universität Wien nach 1917', inst:'Wien' },
    { author:'Caroline Gerschlager', title:'Joseph A. Schumpeter: Über Innovationen in der Politik', inst:'Wien' },
    { author:'Jürgen Backhaus', title:'Oswald Spengler', inst:'Erfurt' },
    { author:'Christian Gehrke', title:'Spuren einer Lebensreise: Georg von Charasoff (1877–1931)', inst:'Graz' },
    { author:'Toni Pierenkemper', title:'Ein wahrer Außenseiter unter Außenseitern: Oskar Stillich', inst:'Köln' },
    { author:'Günther Chaloupek', title:'Die neue Wirtschaft und Von kommenden Dingen – Walther Rathenau als Ökonom und Sozialphilosoph', inst:'Wien' }
  ] },
  { nr:32, year:2011, dates:'5.–7. Mai 2011', country:'DE', loc_de:'Freiburg im Breisgau', loc_en:'Freiburg im Breisgau', venue:'Liefmann-Haus, Goethestraße 33–35, Freiburg', theme:'Die Entwicklung der Raumwirtschaftslehre von ihren Anfängen bis in die Gegenwart', theme_en:'The Development of Spatial Economics from Its Origins to the Present', vol:'XXIX', papers:[
    { author:'Heinz D. Kurz', title:'Raum in der Ökonomik', inst:'Graz' },
    { author:'Ludwig Nellinger', title:'Thünens umfassendes Raumwirtschaftsmodell', inst:'' },
    { author:'Günther Chaloupek', title:'Stadt und Land – zur Regionalökonomik der Historischen Schule', inst:'Wien' },
    { author:'Karl-Heinz Schmidt', title:'Raumforschung 1930–50: Von der Standorttheorie zu einer Theorie der wirtschaftlichen Raumordnung?', inst:'' },
    { author:'Horst Todt', title:'Christaller und Lösch', inst:'Hamburg' },
    { author:'Johannes Bröcker', title:'Raumforschung im Dritten Reich', inst:'' },
    { author:'Heinz Rieter', title:'Die Beteiligung Friedrich Bülows und Karl C. Thalheims an der NS-Raumforschung (Korreferat)', inst:'Hamburg' },
    { author:'Martin Beckmann', title:'Leonard Mikschs Beitrag zur Theorie der räumlichen Märkte', inst:'' },
    { author:'Hans-Michael Trautwein', title:'Von der Neuen Handelstheorie zur Neuen Wirtschaftsgeographie', inst:'Oldenburg' }
  ] },
  { nr:31, year:2010, dates:'27.–29. Mai 2010', country:'DE', loc_de:'Stuttgart-Hohenheim', loc_en:'Stuttgart-Hohenheim', venue:'Universität Hohenheim', theme:'Die Ökonomik im Spannungsfeld zwischen Natur- und Geisteswissenschaften. Alte und neue Perspektiven im Licht des jüngsten Methodenstreits', theme_en:'Economics between Natural and Humanistic Sciences', vol:'XXVIII', papers:[
    { author:'Karl Milford', title:'Die Methode der Naturwissenschaften im Lichte sozialwissenschaftlicher Methodenlehren des 19. und 20. Jahrhunderts', inst:'Wien' },
    { author:'Elke Muchlinski', title:'Wie zweckmäßig ist das Vorbild der physikalischen Wissenschaft für ökonomische Metaphern?', inst:'' },
    { author:'Alexander Ebner', title:'Ökonomie als Geisteswissenschaft? Grundzüge der Erklären-Verstehen-Kontroverse', inst:'Frankfurt' },
    { author:'Michael Wohlgemuth', title:'Die Kalkulationsdebatte als Methodenstreit', inst:'Witten/Herdecke' },
    { author:'Jürgen Kromphardt', title:'Der jüngste Methodenstreit: Alter Streit in neuem Gewande?', inst:'' },
    { author:'Bertram Schefold', title:'Der Ökonom Max Weber zwischen der Soziologie der Wirtschaftsethik und der rationalen Theorie rationalen Handelns', inst:'Frankfurt' },
    { author:'Volker Caspari', title:'Keynes\' Kritik an der Tinbergenschen Ökonometrie', inst:'Darmstadt' },
    { author:'Ingo Barens', title:'Animal Spirits und John Maynard Keynes', inst:'Darmstadt' },
    { author:'Peter Rosner', title:'Die einfache Welt der Quantitätsgleichung und die komplizierte Welt der Finanz', inst:'Wien' }
  ] },
  { nr:30, year:2009, dates:'15.–16. Mai 2009', country:'AT', loc_de:'Wien', loc_en:'Vienna', venue:'Wien', theme:'Geschichte der Entwicklungstheorien', theme_en:'History of Development Theories', vol:'XXXI', papers:[] },
  { nr:29, year:2008, dates:'21.–22. Mai 2008', country:'DE', loc_de:'Berlin', loc_en:'Berlin', venue:'Berlin', theme:'Der Einfluss deutschsprachigen wirtschaftswissenschaftlichen Denkens in Japan', theme_en:'The Influence of German-Language Economic Thought in Japan', vol:'XXVII', papers:[] },
  { nr:28, year:2007, dates:'31. Mai – 2. Juni 2007', country:'DE', loc_de:'Lüdinghausen / Nordkirchen', loc_en:'Lüdinghausen / Nordkirchen', venue:'Schloss Nordkirchen', theme:'Wechselseitige Einflüsse zwischen dem deutschen wirtschaftswissenschaftlichen Denken und dem anderer europäischer Sprachräume', theme_en:'Mutual Influences between German Economic Thought and That of Other European Language Areas', vol:'XXIV', papers:[
    { author:'Christian Gehrke · Heinz D. Kurz', title:'Die Debatte um die Ertrags- und Kostentheorie und ihre Reflektion im deutschen Schrifttum', inst:'Graz' },
    { author:'Vitantonio Gioia', title:'The German Historical School of Economics in the Italian Debate (1870–1890)', inst:'Macerata' },
    { author:'Hauke Janssen', title:'Alexander W. Tschajanow (1888–1937) und die russische Emigration in Deutschland', inst:'Hamburg' },
    { author:'Elke Muchlinski', title:'Die Maynard Keynes-Manuskripte von 1904 bis 1911 und ihre Rezeption im englisch/versus deutschsprachigen Raum', inst:'FU Berlin' },
    { author:'Peter Rosner', title:'Die Theorie von Karl Marx als Antwort auf die von Pierre-Joseph Proudhon gestellten Fragen', inst:'Wien' },
    { author:'Hans-Michael Trautwein · Bo Sandelin', title:'Mutual influences of economists in the German and Swedish language areas', inst:'Oldenburg · Göteborg' },
    { author:'Keith Tribe', title:'Das Adam Smith Problem und die deutsche Rezeption', inst:'Sussex' },
    { author:'Joachim Zweynert', title:'Deutsche Einflüsse auf das russische ökonomische Denken in der ersten Hälfte des 19. Jahrhunderts', inst:'HWWA Hamburg' }
  ] },
  { nr:27, year:2006, dates:'18.–20. Mai 2006', country:'AT', loc_de:'Graz', loc_en:'Graz', venue:'Karl-Franzens-Universität Graz', theme:'Wissen = The Knowledge Economy', theme_en:'Wissen = The Knowledge Economy', vol:'XXVI', papers:[
    { author:'Dieter Schneider', title:'Auf der Suche nach den Anfängen einer Wissensökonomie', inst:'Bochum' },
    { author:'Ernst Helmstädter', title:'Das gesellschaftliche Wissen als Reichtumsquelle – Seine Bedeutungsschwankungen von Adam Smith bis heute', inst:'Münster' },
    { author:'Tetsushi Harada', title:'Die Verortung der öffentlichen Meinung in der Wertbestimmung bei der älteren deutschen Gebrauchswertschule', inst:'Yokkaichi' },
    { author:'Yuichi Shionoya', title:'Knowledge about the Knowledge Economy in the Schumpeterian Perspective', inst:'Tokio' },
    { author:'Kurt Dopfer', title:'Reading Schumpeter as if Knowledge Mattered', inst:'St. Gallen' }
  ] },
  { nr:26, year:2005, dates:'2005', country:'DE', loc_de:'Berlin', loc_en:'Berlin', venue:'Berlin', theme:'Deutsche Einflüsse auf amerikanisches wirtschaftswissenschaftliches Denken und amerikanische Einflüsse auf deutsches Wirtschaftsdenken', theme_en:'German Influences on American Economic Thought and American Influences on German Economic Thought', vol:'XXXII', papers:[] },
  { nr:25, year:2004, dates:'2004', country:'DE', loc_de:'Bonn', loc_en:'Bonn', venue:'Bonn', theme:'Wirtschaftswissenschaft und Technik', theme_en:'Economics and Technology', vol:'XXIII', papers:[] },
  { nr:24, year:2003, dates:'2003', country:'DE', loc_de:'Oldenburg', loc_en:'Oldenburg', venue:'Oldenburg', theme:'Ökonomie und Religion', theme_en:'Economics and Religion', vol:'XXI', papers:[] },
  { nr:23, year:2002, dates:'2002', country:'AT', loc_de:'Obermayerhofen bei Graz', loc_en:'Obermayerhofen near Graz', venue:'Obermayerhofen', theme:'Die deutschsprachige Wirtschaftswissenschaft in den ersten Jahrzehnten nach 1945 (II)', theme_en:'German-Language Economics in the First Decades after 1945, Part II', vol:'XXV', papers:[] },
  { nr:22, year:2001, dates:'2001', country:'DE', loc_de:'Hamburg', loc_en:'Hamburg', venue:'Hamburg', theme:'Die deutschsprachige Wirtschaftswissenschaft in den ersten Jahrzehnten nach 1945 (I)', theme_en:'German-Language Economics in the First Decades after 1945, Part I', vol:'XXII', papers:[] },
  { nr:21, year:2000, dates:'2000', country:'AT', loc_de:'Wien', loc_en:'Vienna', venue:'Wien', theme:'Ideen, Methoden und Entwicklungen der Geschichte des ökonomischen Denkens', theme_en:'Ideas, Methods and Developments in the History of Economic Thought', vol:null, papers:[] },
  { nr:20, year:1999, dates:'1999', country:'DE', loc_de:'Ulm', loc_en:'Ulm', venue:'Ulm', theme:'Die Ältere Historische Schule: Wirtschaftstheoretische Beiträge und wirtschaftspolitische Vorstellungen', theme_en:'The Older Historical School: Contributions to Economic Theory and Economic Policy', vol:'XX', papers:[] },
  { nr:19, year:1998, dates:'1998', country:'DE', loc_de:'Würzburg', loc_en:'Würzburg', venue:'Würzburg', theme:'John Stuart Mill', theme_en:'John Stuart Mill', vol:'XIX', papers:[] },
  { nr:18, year:1997, dates:'1997', country:'DE', loc_de:'Stuttgart-Hohenheim', loc_en:'Stuttgart-Hohenheim', venue:'Universität Hohenheim', theme:'Knut Wicksell', theme_en:'Knut Wicksell', vol:'XVIII', papers:[] },
  { nr:17, year:1996, dates:'1996', country:'NL', loc_de:'Maastricht', loc_en:'Maastricht', venue:'Maastricht', theme:'Die Umsetzung wirtschaftspolitischer Grundkonzeptionen in die kontinentaleuropäische Praxis des 19. und 20. Jahrhunderts (II)', theme_en:'The Implementation of Economic Policy Principles in Continental European Practice, 19th–20th Century, Part II', vol:'XVII', papers:[] },
  { nr:16, year:1995, dates:'1995', country:'AT', loc_de:'Salzburg', loc_en:'Salzburg', venue:'Salzburg', theme:'Die Umsetzung wirtschaftspolitischer Grundkonzeptionen in die kontinentaleuropäische Praxis des 19. und 20. Jahrhunderts (I)', theme_en:'The Implementation of Economic Policy Principles in Continental European Practice, 19th–20th Century, Part I', vol:'XVI', papers:[] },
  { nr:15, year:1994, dates:'1994', country:'DE', loc_de:'Weimar', loc_en:'Weimar', venue:'Weimar', theme:'Revolution und Evolution in der Wirtschaftstheorie', theme_en:'Revolution and Evolution in Economic Theory', vol:null, papers:[] },
  { nr:14, year:1993, dates:'1993', country:'DE', loc_de:'Tellow', loc_en:'Tellow', venue:'Tellow', theme:'Johann Heinrich von Thünen als Wirtschaftstheoretiker', theme_en:'Johann Heinrich von Thünen as Economic Theorist', vol:'XIV', papers:[] },
  { nr:13, year:1992, dates:'1992', country:'DE', loc_de:'Augsburg', loc_en:'Augsburg', venue:'Augsburg', theme:'Deutsche Finanzwissenschaft zwischen 1918 und 1939', theme_en:'German Public Finance between 1918 and 1939', vol:'XIII', papers:[] },
  { nr:12, year:1991, dates:'1991', country:'CH', loc_de:'Ittingen (Schweiz)', loc_en:'Ittingen (Switzerland)', venue:'Kartause Ittingen, Thurgau', theme:'Osteuropäische Dogmengeschichte', theme_en:'Eastern European History of Economic Doctrines', vol:'XII', papers:[] },
  { nr:11, year:1990, dates:'1990', country:'DE', loc_de:'Frankfurt am Main', loc_en:'Frankfurt am Main', venue:'Frankfurt am Main', theme:'Darstellung der Wirtschaft und Wirtschaftswissenschaften in der Belletristik', theme_en:'The Representation of Economics and Economists in Literature', vol:'XI', papers:[] },
  { nr:10, year:1989, dates:'1989', country:'DE', loc_de:'Tübingen', loc_en:'Tübingen', venue:'Tübingen', theme:'Friedrich List; Carl Menger; Lorenz von Stein', theme_en:'Friedrich List; Carl Menger; Lorenz von Stein', vol:'X', papers:[] },
  { nr:9, year:1988, dates:'1988', country:'DE', loc_de:'Berlin', loc_en:'Berlin', venue:'Berlin', theme:'Deutschsprachige Wirtschafts-, Konjunktur- und Geldtheorie in der ersten Hälfte des 20. Jahrhunderts', theme_en:'German-Language Economic, Business Cycle, and Monetary Theory in the First Half of the 20th Century', vol:'IX', papers:[] },
  { nr:8, year:1987, dates:'1987', country:'DE', loc_de:'Würzburg', loc_en:'Würzburg', venue:'Würzburg', theme:'Konjunkturtheorie im ausgehenden 19. Jahrhundert', theme_en:'Business Cycle Theory in the Late 19th Century', vol:'VII', papers:[] },
  { nr:7, year:1986, dates:'1986', country:'DE', loc_de:'Stuttgart', loc_en:'Stuttgart', venue:'Stuttgart', theme:'Allgemeine Gleichgewichtsanalyse', theme_en:'General Equilibrium Analysis', vol:null, papers:[] },
  { nr:6, year:1985, dates:'1985', country:'DE', loc_de:'Münster', loc_en:'Münster', venue:'Münster', theme:'Entwicklungen der deutschsprachigen Nationalökonomie im 19. Jahrhundert', theme_en:'Developments in German Political Economy in the 19th Century', vol:'VI', papers:[] },
  { nr:5, year:1984, dates:'1984', country:'AT', loc_de:'Salzburg', loc_en:'Salzburg', venue:'Salzburg', theme:'Deutsche Nationalökonomie Ende des 18. und in der ersten Hälfte des 19. Jahrhunderts', theme_en:'German Political Economy at the End of the 18th and in the First Half of the 19th Century', vol:'V', papers:[] },
  { nr:4, year:1983, dates:'1983', country:'DE', loc_de:'Göttingen', loc_en:'Göttingen', venue:'Göttingen', theme:'Marx, Keynes, Schumpeter', theme_en:'Marx, Keynes, Schumpeter', vol:'IV', papers:[] },
  { nr:3, year:1982, dates:'1982', country:'CH', loc_de:'Basel', loc_en:'Basel', venue:'Basel', theme:'Theoriegeschichte – wozu?', theme_en:'History of Economic Thought – What For?', vol:'III', papers:[] },
  { nr:2, year:1981, dates:'1981', country:'AT', loc_de:'Salzburg', loc_en:'Salzburg', venue:'Salzburg', theme:'Merkantilismus und Kameralismus', theme_en:'Mercantilism and Cameralism', vol:'II', papers:[] },
  { nr:1, year:1980, dates:'1980', country:'DE', loc_de:'Gießen', loc_en:'Giessen', venue:'Justus-Liebig-Universität Gießen', theme:'Klassische Nationalökonomie', theme_en:'Classical Political Economy', vol:'I', papers:[] },
];

const DH_SEARCH = 'https://www.duncker-humblot.de/search/result?schnellsuche=Studien%20zur%20Entwicklung%20der%20%C3%B6konomischen%20Theorie&sort=datum_erscheinung_jahr%20desc%2Cdatum_erscheinung%20desc&page=1&type=titel&nav_id=1';

const PUBLICATIONS = [
  { num:'I', numN:1, year:null, decade:'1980s', title_de:'Klassische Themen der Dogmengeschichte', title_en:'Classical Themes in the History of Economic Doctrines', editor:'', url:DH_SEARCH },
  { num:'II', numN:2, year:null, decade:'1980s', title_de:'Geschichte merkantilistischer Ideen und Praktiken', title_en:'History of Mercantilist Ideas and Practices', editor:'hrsg. v. Fritz Neumark', url:DH_SEARCH },
  { num:'III', numN:3, year:null, decade:'1980s', title_de:'Bedeutung und Fortwirkung der Physiokraten', title_en:'The Significance and Continuing Influence of the Physiocrats', editor:'hrsg. v. Harald Scherf', url:DH_SEARCH },
  { num:'IV', numN:4, year:1983, decade:'1980s', title_de:'Drei Jubiäen (1983): Karl Marx – Joseph Schumpeter – John Maynard Keynes', title_en:'Three Anniversaries (1983): Karl Marx -- Joseph Schumpeter -- John Maynard Keynes', editor:'hrsg. v. Harald Scherf', url:DH_SEARCH },
  { num:'V', numN:5, year:null, decade:'1980s', title_de:'Deutsche Nationalökonomie zu Beginn des 19. Jahrhunderts', title_en:'German Political Economy at the Beginning of the 19th Century', editor:'hrsg. v. Harald Scherf', url:DH_SEARCH },
  { num:'VI', numN:6, year:null, decade:'1980s', title_de:'Deutsche Nationalökonomie im 19. Jahrhundert', title_en:'German Political Economy in the 19th Century', editor:'hrsg. v. Harald Scherf', url:DH_SEARCH },
  { num:'VII', numN:7, year:null, decade:'1980s', title_de:'Konjunkturtheorie im ausgehenden 19. Jahrhundert', title_en:'Business Cycle Theory in the Late 19th Century', editor:'hrsg. v. Bertram Schefold', url:DH_SEARCH },
  { num:'VIII', numN:8, year:null, decade:'1980s', title_de:'Deutsche Nationalökonomie in der Zwischenkriegszeit', title_en:'German Political Economy in the Interwar Period', editor:'hrsg. v. Bertram Schefold', url:DH_SEARCH },
  { num:'IX', numN:9, year:1990, decade:'1990s', title_de:'Untersuchungen zu Quesnay, Stein, Jevons und zur allgemeinen Gleichgewichtstheorie', title_en:'Studies on Quesnay, Stein, Jevons and General Equilibrium Theory', editor:'hrsg. v. Harald Scherf', url:DH_SEARCH },
  { num:'X', numN:10, year:1991, decade:'1990s', title_de:'Friedrich List: Voraussetzungen und Folgen', title_en:'Friedrich List: Premises and Consequences', editor:'hrsg. v. Bertram Schefold', url:DH_SEARCH },
  { num:'XI', numN:11, year:1992, decade:'1990s', title_de:'Die Darstellung der Wirtschaft und der Wirtschaftswissenschaften in der Belletristik', title_en:'The Representation of Economics and Economists in Literature', editor:'hrsg. v. Bertram Schefold', url:DH_SEARCH },
  { num:'XII', numN:12, year:null, decade:'1990s', title_de:'Osteuropäische Dogmengeschichte', title_en:'Eastern European History of Economic Doctrines', editor:'hrsg. v. Heinz Rieter', url:DH_SEARCH },
  { num:'XIII', numN:13, year:1993, decade:'1990s', title_de:'Deutsche Finanzwissenschaft zwischen 1918 und 1939', title_en:'German Public Finance between 1918 and 1939', editor:'hrsg. v. Christian Scheer', url:'https://www.duncker-humblot.de/buch/studien-zur-entwicklung-der-oekonomischen-theorie-xiii-9783428078615/' },
  { num:'XIV', numN:14, year:1995, decade:'1990s', title_de:'Johann Heinrich von Thünen als Wirtschaftstheoretiker', title_en:'Johann Heinrich von Th\"unen as Economic Theorist', editor:'hrsg. v. Heinz Rieter', url:'https://www.duncker-humblot.de/buch/johann-heinrich-von-th%C3%BCnen-als-wirtschaftstheoretiker-9783428484584/' },
  { num:'XV', numN:15, year:1996, decade:'1990s', title_de:'Wege und Ziele der Forschung', title_en:'Paths and Goals of Research', editor:'hrsg. v. Heinz Rieter', url:'https://www.duncker-humblot.de/buch/studien-zur-entwicklung-der-oekonomischen-theorie-xv-9783428484928/' },
  { num:'XVI', numN:16, year:1997, decade:'1990s', title_de:'Die Umsetzung wirtschaftspolitischer Grundkonzeptionen in die kontinentaleuropäische Praxis des 19. und 20. Jahrhunderts, I. Teil', title_en:'The Implementation of Economic Policy Principles in Continental European Practice, 19th--20th Century, Part~I', editor:'hrsg. v. Erich W. Streissler', url:DH_SEARCH },
  { num:'XVII', numN:17, year:null, decade:'1990s', title_de:'Die Umsetzung wirtschaftspolitischer Grundkonzeptionen in die kontinentaleuropäische Praxis des 19. und 20. Jahrhunderts, II. Teil', title_en:'The Implementation of Economic Policy Principles in Continental European Practice, 19th--20th Century, Part~II', editor:'hrsg. v. Erich W. Streissler', url:DH_SEARCH },
  { num:'XVIII', numN:18, year:null, decade:'1990s', title_de:'Knut Wicksell als Ökonom', title_en:'Knut Wicksell as Economist', editor:'hrsg. v. Erich W. Streissler', url:DH_SEARCH },
  { num:'XIX', numN:19, year:null, decade:'1990s', title_de:'John Stuart Mill', title_en:'John Stuart Mill', editor:'hrsg. v. Erich W. Streissler', url:DH_SEARCH },
  { num:'XX', numN:20, year:null, decade:'2000s', title_de:'Die Ältere Historische Schule: Wirtschaftstheoretische Beiträge und wirtschaftspolitische Vorstellungen', title_en:'The Older Historical School: Contributions to Economic Theory and Economic Policy', editor:'hrsg. v. Christian Scheer', url:DH_SEARCH },
  { num:'XXI', numN:21, year:null, decade:'2000s', title_de:'Ökonomie und Religion', title_en:'Economics and Religion', editor:'hrsg. v. Harald Hagemann', url:DH_SEARCH },
  { num:'XXII', numN:22, year:null, decade:'2000s', title_de:'Ideen, Methoden und Entwicklungen der Geschichte des ökonomischen Denkens', title_en:'Ideas, Methods and Developments in the History of Economic Thought', editor:'hrsg. v. Christian Scheer', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/285797' },
  { num:'XXIII', numN:23, year:null, decade:'2000s', title_de:'Ökonomie und Technik', title_en:'Economics and Technology', editor:'hrsg. v. Harald Hagemann', url:DH_SEARCH },
  { num:'XXIV', numN:24, year:null, decade:'2000s', title_de:'Wechselseitige Einflüsse zwischen dem deutschen wirtschaftswissenschaftlichen Denken und dem anderer europäischer Sprachräume', title_en:'Mutual Influences between German Economic Thought and That of Other European Language Areas', editor:'hrsg. v. Heinz D. Kurz', url:DH_SEARCH },
  { num:'XXV', numN:25, year:null, decade:'2000s', title_de:'Die deutschsprachige Wirtschaftswissenschaft in den ersten Jahrzehnten nach 1945', title_en:'German-Language Economics in the First Decades after 1945', editor:'hrsg. v. Christian Scheer', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/285805' },
  { num:'XXVI', numN:26, year:null, decade:'2000s', title_de:'Wissen = The Knowledge Economy', title_en:'Wissen = The Knowledge Economy', editor:'hrsg. v. Harald Hagemann', url:DH_SEARCH },
  { num:'XXVII', numN:27, year:null, decade:'2000s', title_de:'Der Einfluss deutschsprachigen wirtschaftswissenschaftlichen Denkens in Japan', title_en:'The Influence of German-Language Economic Thought in Japan', editor:'hrsg. v. Heinz D. Kurz', url:DH_SEARCH },
  { num:'XXVIII', numN:28, year:2014, decade:'2000s', title_de:'Die Ökonomik im Spannungsfeld zwischen Natur- und Geisteswissenschaften: Alte und neue Perspektiven im Licht des jüngsten Methodenstreits', title_en:'Economics between Natural and Humanistic Sciences', editor:'hrsg. v. Heinz D. Kurz', url:DH_SEARCH },
  { num:'XXIX', numN:29, year:null, decade:'2000s', title_de:'Die Entwicklung der Raumwirtschaftslehre von ihren Anfängen bis in die Gegenwart', title_en:'The Development of Spatial Economics from Its Origins to the Present', editor:'hrsg. v. Hans-Michael Trautwein', url:DH_SEARCH },
  { num:'XXX', numN:30, year:null, decade:'2000s', title_de:'Die Zeit um den Ersten Weltkrieg als Krisenzeit der Ökonomen', title_en:'The Era of the First World War as a Crisis Period for Economists', editor:'hrsg. v. Hans-Michael Trautwein', url:DH_SEARCH },
  { num:'XXXI', numN:31, year:null, decade:'2010s', title_de:'Geschichte der Entwicklungstheorien', title_en:'History of Development Theories', editor:'hrsg. v. Heinz D. Kurz', url:DH_SEARCH },
  { num:'XXXII', numN:32, year:null, decade:'2010s', title_de:'Deutsche Einflüsse auf amerikanisches wirtschaftswissenschaftliches Denken und amerikanische Einflüsse auf deutsches Wirtschaftsdenken', title_en:'German Influences on American Economic Thought and American Influences on German Economic Thought', editor:'hrsg. v. Heinz D. Kurz und Volker Caspari', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/285828' },
  { num:'XXXIV', numN:34, year:null, decade:'2010s', title_de:'Neue Perspektiven auf die Politische Ökonomie von Karl Marx und Friedrich Engels: Die Marx-Engels-Gesamtausgabe (MEGA)', title_en:'New Perspectives on the Political Economy of Marx and Engels: The Marx-Engels-Gesamtausgabe (MEGA)', editor:'hrsg. v. Hans-Michael Trautwein', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/285830' },
  { num:'XXXV', numN:35, year:null, decade:'2010s', title_de:'Macht oder ökonomisches Gesetz?', title_en:'Political Control or Economic Law?', editor:'hrsg. v. Hans-Michael Trautwein', url:DH_SEARCH },
  { num:'XXXVI', numN:36, year:null, decade:'2010s', title_de:'Ökonomie und Evolution', title_en:'Economics and Evolution', editor:'hrsg. v. Peter Spahn', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/286113' },
  { num:'XXXVII', numN:37, year:null, decade:'2010s', title_de:'Einkommens- und Vermögensverteilung in historischer Sicht', title_en:'Income and Wealth Distribution in Historical Perspective', editor:'hrsg. v. Volker Caspari', url:DH_SEARCH },
  { num:'XXXIX', numN:39, year:2022, decade:'2010s', title_de:'Kameralismus und Merkantilismus', title_en:'Cameralism and Mercantilism', editor:'hrsg. v. Volker Caspari', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/286115' },
  { num:'XL', numN:40, year:null, decade:'2010s', title_de:'Entwicklung der Konjunkturforschung im frühen 20. Jahrhundert', title_en:'Development of Business Cycle Research in the Early 20th Century', editor:'', url:DH_SEARCH },
  { num:'XLI', numN:41, year:null, decade:'2010s', title_de:'Zur Geschichte des Vereins für Socialpolitik', title_en:'Zur Geschichte des Vereins f{\"u}r Socialpolitik', editor:'hrsg. v. Peter Spahn', url:DH_SEARCH, econstor:'https://directory.doabooks.org/handle/20.500.12854/121170' },
  { num:'XLII', numN:42, year:null, decade:'2010s', title_de:'Adam Smith @ 300', title_en:'Adam Smith @ 300', editor:'', url:DH_SEARCH, econstor:'https://www.econstor.eu/handle/10419/301208' },
];

const FMTS = [
    { id: 'bibtex',  label: 'BibTeX',      ext: 'bib' },
    { id: 'endnote', label: 'EndNote',      ext: 'enw' },
    { id: 'ris',     label: 'RIS / Zotero', ext: 'ris' },
    { id: 'chicago', label: 'Chicago',      ext: 'txt' },
  ];

const ANNOUNCEMENTS=[
  {date:'2026-05-29',icon:'\U0001F310',
   title_de:'Website der 46. Jahrestagung online',title_en:'Conference website launched',
   text_de:'Die offizielle Konferenzwebsite f\u00fcr Riva San Vitale ist jetzt zug\u00e4nglich.',
   text_en:'The official website for the 46th Jahrestagung is now live.'},
  {date:'2026-04-01',icon:'\U0001F4C4',
   title_de:'Tagungsprogramm best\u00e4tigt',title_en:'Academic programme confirmed',
   text_de:'Das wissenschaftliche Programm ist vollst\u00e4ndig best\u00e4tigt: 10 Vortr\u00e4ge zu den Zukunftsperspektiven der Theoriegeschichte.',
   text_en:'The full academic programme has been confirmed: 10 papers on the future of the history of economic thought.'},
  {date:'2026-03-15',icon:'\U0001F4DA',
   title_de:'Band XLII (Edinburgh 2023) erschienen',title_en:'Volume XLII published',
   text_de:'Der Tagungsband Adam Smith @ 300 ist beim Verlag Duncker & Humblot erschienen.',
   text_en:'The proceedings volume Adam Smith @ 300 has been published by Duncker & Humblot.'},
];

// Also expose on a namespace object for explicit cross-page access
window.AGW_DATA = {
  CHAIRS: typeof CHAIRS !== 'undefined' ? CHAIRS : undefined,
  MEMBERS: typeof MEMBERS !== 'undefined' ? MEMBERS : undefined,
  ARCHIVE: typeof ARCHIVE !== 'undefined' ? ARCHIVE : undefined,
  PUBLICATIONS: typeof PUBLICATIONS !== 'undefined' ? PUBLICATIONS : undefined,
  FMTS: typeof FMTS !== 'undefined' ? FMTS : undefined,
  ANNOUNCEMENTS: typeof ANNOUNCEMENTS !== 'undefined' ? ANNOUNCEMENTS : undefined
};
