/**
 * agw_hero_viz.js — AGW landing-page hero visualization
 * ─────────────────────────────────────────────────────────────────────────
 * "Denkschulen-Konstellation" — production build on the validated corpus.
 *   • node size   = prominence.factor (the validated PC1 scalar)
 *   • node colour = school of thought (lifted-for-navy palette, from hero_data.py)
 *   • edges       = body-only co-occurrence backbone (footnotes excluded; ADR)
 *   • gold ring   = luminaries (top-N by factor)
 *   • hover node  = pause drift + full-card tooltip (name · dates · school ·
 *                   prominence · Stammbaum link)
 *   • legend chip = hover/focus (desktop) or tap (touch) to highlight one school
 *   • click node  = open Netzwerke → Stammbaum on analytics.html
 *
 * Figure/edge data is EMBEDDED below (no runtime fetch) and regenerated from
 * data/agw_corpus.json + data/agw_proximity_body.json by tools/hero_data.py —
 * never hand-edit the block between the @@HERO-DATA@@ markers. Each figure now
 * carries "s" (school name); the legend + tooltip degrade gracefully if absent
 * (so this file is safe to drop in before the regen has been run).
 *
 * Self-mounts: finds .hero, injects a background <canvas> + scrim behind
 * .hero-inner, an interactive school legend INTO .hero-inner, and a tooltip on
 * <body>. Pure vanilla JS, no dependencies. The "Was uns beschäftigt" rotator
 * reads recent Jahrestagung themes from the global ARCHIVE and follows the DE/EN
 * language toggle. Respects prefers-reduced-motion.
 */
(function () {
  'use strict';

  /* @@HERO-DATA:BEGIN — generated by tools/hero_data.py, do not edit by hand @@ */
  var FIGS = [
    {"n": "Schumpeter", "b": 1883, "d": 1950, "c": "#edc948", "p": 1, "f": 100.0, "id": "schumpeter-joseph-alois", "sid": "schumpeter"},
    {"n": "Hayek", "b": 1899, "d": 1992, "c": "#3FB0A3", "p": 1, "f": 92.4, "id": "hayek-friedrich-august", "sid": "hayek"},
    {"n": "Smith", "b": 1723, "d": 1790, "c": "#C2A06B", "p": 1, "f": 89.2, "id": "smith-adam", "sid": "smith"},
    {"n": "Keynes", "b": 1883, "d": 1946, "c": "#6BB58C", "p": 1, "f": 88.8, "id": "keynes-john-maynard", "sid": "keynes"},
    {"n": "Mill", "b": 1806, "d": 1873, "c": "#C2A06B", "p": 1, "f": 86.5, "id": "mill-john-stuart", "sid": "mill"},
    {"n": "Wicksell", "b": 1851, "d": 1926, "c": "#9AA6D0", "p": 1, "f": 82.4, "id": "wicksell-knut", "sid": "wicksell"},
    {"n": "Röpke", "b": 1899, "d": 1966, "c": "#D6A24A", "p": 1, "f": 81.3, "id": "ropke-wilhelm", "sid": "roepke"},
    {"n": "Eucken", "b": 1891, "d": 1950, "c": "#D6A24A", "p": 1, "f": 77.8, "id": "eucken-walter", "sid": "eucken"},
    {"n": "Samuelson", "b": 1915, "d": 2009, "c": "#9AA6D0", "p": 1, "f": 77.5, "id": "samuelson-paul-anthony", "sid": "samuelson"},
    {"n": "Weber", "b": 1864, "d": 1920, "c": "#6E8FCB", "p": 1, "f": 76.1, "id": "weber-max", "sid": "mweber"},
    {"n": "Sraffa", "b": 1898, "d": 1983, "c": "#7fb3c9", "p": 0, "f": 76.1, "id": "sraffa-piero", "sid": null},
    {"n": "Marshall", "b": 1842, "d": 1924, "c": "#9AA6D0", "p": 0, "f": 75.1, "id": "marshall-alfred", "sid": "marshall"},
    {"n": "Schneider", "b": 1900, "d": 1970, "c": "#9AA6D0", "p": 0, "f": 74.9, "id": "schneider-erich", "sid": null},
    {"n": "Marx", "b": 1818, "d": 1883, "c": "#b07aa1", "p": 0, "f": 74.6, "id": "marx-karl", "sid": "marx"},
    {"n": "Krugman", "b": 1953, "d": null, "c": "#8cd17d", "p": 0, "f": 74.2, "id": "krugman-paul-robin", "sid": null},
    {"n": "Menger", "b": 1840, "d": 1921, "c": "#3FB0A3", "p": 0, "f": 74.1, "id": "menger-carl", "sid": "menger"},
    {"n": "Patinkin", "b": 1922, "d": 1995, "c": "#6BB58C", "p": 0, "f": 71.5, "id": "patinkin-don", "sid": null},
    {"n": "Ricardo", "b": 1772, "d": 1823, "c": "#C2A06B", "p": 0, "f": 71.2, "id": "ricardo-david", "sid": "ricardo"},
    {"n": "Sombart", "b": 1863, "d": 1941, "c": "#6E8FCB", "p": 0, "f": 70.8, "id": "sombart-werner", "sid": "sombart"},
    {"n": "Friedman", "b": 1912, "d": 2006, "c": "#9AA6D0", "p": 0, "f": 70.7, "id": "friedman-milton", "sid": "friedman"},
    {"n": "Hildebrand", "b": 1812, "d": 1878, "c": "#6E8FCB", "p": 0, "f": 70.6, "id": "hildebrand-bruno", "sid": "hildebrand"},
    {"n": "Blaug", "b": 1927, "d": 2011, "c": "#bab0ac", "p": 0, "f": 69.1, "id": "blaug-mark", "sid": null},
    {"n": "Böhm-Bawerk", "b": 1851, "d": 1914, "c": "#3FB0A3", "p": 0, "f": 66.6, "id": "bohm-bawerk-eugen", "sid": "boehm"},
    {"n": "Myrdal", "b": 1898, "d": 1987, "c": "#e79ab0", "p": 0, "f": 65.6, "id": "myrdal-gunnar", "sid": "myrdal"},
    {"n": "Roscher", "b": 1817, "d": 1894, "c": "#6E8FCB", "p": 0, "f": 65.5, "id": "roscher-wilhelm-georg-friedrich", "sid": "roscher"},
    {"n": "Neisser", "b": 1895, "d": 1975, "c": "#3FB0A3", "p": 0, "f": 64.6, "id": "neisser-hans-philip", "sid": null},
    {"n": "Häuser", "b": 1920, "d": 2002, "c": "#bab0ac", "p": 0, "f": 63.8, "id": "hauser-karl", "sid": null},
    {"n": "Lowe", "b": 1893, "d": 1995, "c": "#e79ab0", "p": 0, "f": 63.7, "id": "lowe-adolph", "sid": null},
    {"n": "Salin", "b": 1892, "d": 1974, "c": "#6E8FCB", "p": 0, "f": 63.5, "id": "salin-edgar", "sid": null},
    {"n": "Neumark", "b": 1900, "d": 1991, "c": "#8892A6", "p": 0, "f": 63.0, "id": "neumark-fritz", "sid": null},
    {"n": "Mises", "b": 1881, "d": 1973, "c": "#3FB0A3", "p": 0, "f": 62.9, "id": "mises-ludwig", "sid": "mises"},
    {"n": "Lösch", "b": 1906, "d": 1945, "c": "#8cd17d", "p": 0, "f": 62.6, "id": "losch-august", "sid": "loesch"},
    {"n": "Leijonhufvud", "b": 1933, "d": 2022, "c": "#6BB58C", "p": 0, "f": 61.5, "id": "leijonhufvud-axel", "sid": null},
    {"n": "Hicks", "b": 1904, "d": 1989, "c": "#9AA6D0", "p": 0, "f": 60.8, "id": "hicks-john-richard", "sid": "hicks"}
  ];
  var EDGES = [[9,18,1.0], [0,31,0.932], [1,30,0.93], [0,3,0.883], [2,17,0.883], [18,28,0.883], [2,13,0.861], [1,3,0.833], [0,18,0.819], [0,13,0.815], [3,7,0.789], [13,18,0.784], [0,1,0.773], [9,28,0.773], [13,17,0.773], [10,13,0.761], [7,31,0.742], [0,9,0.735], [0,22,0.728], [6,7,0.689], [12,26,0.689], [20,24,0.689], [3,12,0.68], [0,12,0.68], [11,17,0.671], [13,22,0.671], [3,25,0.671], [9,31,0.652], [6,12,0.641], [3,19,0.641], [1,27,0.641], [14,23,0.63], [3,5,0.619], [25,27,0.619], [5,22,0.606], [0,5,0.593], [3,6,0.593], [5,23,0.593], [8,33,0.58], [3,10,0.58], [1,25,0.58], [13,33,0.58], [0,2,0.565], [4,17,0.565], [9,24,0.565], [2,4,0.549], [8,12,0.549], [15,22,0.549], [0,30,0.549], [4,13,0.532], [10,11,0.532], [3,11,0.532], [2,24,0.513], [1,15,0.493], [0,15,0.47], [0,27,0.47], [24,28,0.47], [1,33,0.47], [1,19,0.445], [12,19,0.445], [26,29,0.445], [6,30,0.445], [5,8,0.416], [11,14,0.416], [3,16,0.416], [21,31,0.383], [2,20,0.297], [17,21,0.297], [2,23,0.297], [0,26,0.297], [9,14,0.235], [16,32,0.235], [15,20,0.235], [9,21,0.235], [2,29,0.235], [3,29,0.235], [5,32,0.235]];
  /* @@HERO-DATA:END@@ */

  var reduce = window.matchMedia && window.matchMedia('(prefers-reduced-motion:reduce)').matches;
  var canHover = window.matchMedia && window.matchMedia('(hover:hover) and (pointer:fine)').matches;
  var GOLD = '#E8C674';                    // luminary ring — a brighter gold than any school hue

  function hexa(hex, a) {
    var n = hex.replace('#', '');
    return 'rgba(' + parseInt(n.substr(0,2),16) + ',' + parseInt(n.substr(2,2),16) + ',' + parseInt(n.substr(4,2),16) + ',' + a + ')';
  }
  function dates(f){ if(f.b && f.d) return f.b + '\u2013' + f.d; if(f.b) return f.b + '\u2013'; return ''; }

  // ── language + school labels ───────────────────────────────────────────────
  function lang(){ return (window.AGW && window.AGW.getLang) ? window.AGW.getLang() : 'de'; }

  // Display labels keyed on the English school name emitted by tools/hero_data.py
  // (same keys + palette as agw_schools_net.js). DE labels confirmed by DB;
  // "Contemporary" is intentionally left un-translated, and Raumwirtschaftslehre
  // reads "Spatial Economics" in EN.
  var SCHOOL_LABELS = {
    'Austrian School':          { de: 'Österreichische Schule',      en: 'Austrian School' },
    'Classical':                { de: 'Klassik',                     en: 'Classical' },
    'Contemporary':             { de: 'Contemporary',                en: 'Contemporary' },
    'Development Economics':     { de: 'Entwicklungsökonomik',        en: 'Development Economics' },
    'Evolutionary':             { de: 'Evolutorische Ökonomik',      en: 'Evolutionary' },
    'Historical School':        { de: 'Historische Schule',          en: 'Historical School' },
    'Institutional':            { de: 'Institutionenökonomik',       en: 'Institutional' },
    'Keynesian':                { de: 'Keynesianismus',              en: 'Keynesian' },
    'Marxist':                  { de: 'Marxismus',                   en: 'Marxist' },
    'Neoclassical':             { de: 'Neoklassik',                  en: 'Neoclassical' },
    'Ordoliberalismus':         { de: 'Ordoliberalismus',            en: 'Ordoliberalism' },
    'Philosophy':               { de: 'Philosophie',                 en: 'Philosophy' },
    'Post-Keynesian/Sraffian':  { de: 'Post-Keynesianismus / Sraffa', en: 'Post-Keynesian / Sraffian' },
    'Raumwirtschaftslehre':     { de: 'Raumwirtschaftslehre',        en: 'Spatial Economics' }
  };
  var SCHOOL_FALLBACK = { de: 'ohne Zuordnung', en: 'Unassigned' };
  function schoolLabel(s){
    var L = s && SCHOOL_LABELS[s];
    if (!L) return SCHOOL_FALLBACK[lang()] || SCHOOL_FALLBACK.de;
    return L[lang()] || L.en || s;
  }

  // Tooltip UI strings — inlined (vanilla-panel precedent, cf. agw_schools_net.js)
  var STR = {
    prominence: { de: 'Prominenz',                          en: 'Prominence' },
    luminary:   { de: 'Leitfigur',                          en: 'Luminary' },
    open:       { de: 'Klicken → im Stammbaum öffnen',      en: 'Click → open in the family tree' },
    openTap:    { de: 'Im Stammbaum öffnen',                en: 'Open in the family tree' },
    close:      { de: 'Schließen',                          en: 'Close' },
    notree:     { de: 'nicht im Stammbaum verzeichnet',     en: 'not in the family tree' },
    legendAria: { de: 'Denkschulen — in der Konstellation hervorheben', en: 'Schools of thought — highlight in the constellation' }
  };
  function tr(k){ return STR[k][lang()] || STR[k].de; }

  // Small seeded PRNG (mulberry32) — makes the force layout deterministic so
  // re-sizing the canvas never reshuffles the constellation into a new shape.
  function makeRng(seed){ return function(){ seed |= 0; seed = seed + 0x6D2B79F5 | 0; var t = Math.imul(seed ^ seed >>> 15, 1 | seed); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }

  function init() {
    var hero = document.querySelector('.hero');
    if (!hero) return;                                            // guard
    if (document.getElementById('hero-network-canvas')) return;   // idempotent

    var cv = document.createElement('canvas');
    cv.id = 'hero-network-canvas';
    cv.setAttribute('aria-hidden', 'true');
    cv.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;z-index:0;' +
      'pointer-events:auto;';   // desktop hover + mobile tap-to-inspect (scroll preserved via passive touch handlers)
    var scrim = document.createElement('div');
    scrim.setAttribute('aria-hidden', 'true');
    scrim.style.cssText = 'position:absolute;inset:0;z-index:1;pointer-events:none;' +
      'background:radial-gradient(115% 105% at 12% 42%, rgba(18,40,82,.55) 0%, rgba(18,40,82,.12) 48%, rgba(18,40,82,0) 70%),' +
      'linear-gradient(180deg, rgba(18,40,82,.10), rgba(18,40,82,.30));';
    hero.insertBefore(scrim, hero.firstChild);
    hero.insertBefore(cv, hero.firstChild);
    var inner = hero.querySelector('.hero-inner');
    if (inner) {
      inner.style.position = 'relative'; inner.style.zIndex = '2';
      // The centered .hero-inner box overlaps the constellation's right half; on
      // desktop let pointer events fall through it to the canvas, but keep its
      // real interactive children (rotator hover, any links/buttons) live.
      // Let taps/clicks fall through the (mostly empty) centered text box to the
      // canvas beneath, keeping its real interactive children live. Applies on
      // touch too, so mobile tap-to-inspect can reach nodes under the text box.
      // (.hero-inner holds only text + the rotator — no links/buttons — so this
      // is safe; legend chips re-enable themselves in buildLegend.)
      inner.style.pointerEvents = 'none';
      var live = inner.querySelectorAll('a, button, .hero-rotator');
      for (var q = 0; q < live.length; q++) live[q].style.pointerEvents = 'auto';
    }

    // full-card tooltip (desktop hover) — on <body> so position:fixed can clamp
    // to the viewport regardless of the hero's stacking context
    // Tooltip / inspect card — created in both modes. Desktop: hover-driven,
    // pointer-transparent. Mobile: tap-driven, interactive (Stammbaum button + close).
    var tip = document.createElement('div');
    tip.className = 'hero-tip' + (canHover ? '' : ' hero-tip-tap');
    tip.setAttribute('aria-hidden', 'true');
    if (!canHover) tip.style.pointerEvents = 'auto';
    document.body.appendChild(tip);

    var ctx = cv.getContext('2d');
    var W = 0, H = 0, DPR = Math.min(window.devicePixelRatio || 1, 2), raf = null, nodes = [];
    var t = 0, paused = false, hoverIdx = -1, neigh = [];
    var schoolHover = null, schoolActive = null;   // legend-driven highlight (transient / sticky)

    // factor → radius mapping (a render tunable, not baked into the data)
    var fs = FIGS.map(function (f) { return f.f; });
    var FMIN = Math.min.apply(null, fs), FMAX = Math.max.apply(null, fs);
    function radius(f) {
      var span = (FMAX - FMIN) || 1;
      var r = 2.4 + ((f.f - FMIN) / span) * (6.6 - 2.4);
      return f.p ? r + 0.8 : r;
    }

    // adjacency (for hover neighbour highlighting)
    var ADJ = FIGS.map(function () { return []; });
    EDGES.forEach(function (e) { ADJ[e[0]].push(e[1]); ADJ[e[1]].push(e[0]); });

    function layout() {
      // light Fruchterman–Reingold pass so the real backbone reads as structure
      var wide = W > 860;
      var mL = wide ? W * 0.42 : W * 0.06;   // reserve the left for the hero text on desktop
      var mR = W * 0.05, mT = H * 0.08, mB = H * 0.08;
      var iw = W - mL - mR, ih = H - mT - mB;
      var k = Math.sqrt((iw * ih) / FIGS.length) * 0.55, cx = mL + iw / 2, cy = H / 2;
      var rnd = makeRng(0x5F3759DF);   // deterministic seed → stable layout across resizes (no reshuffle)
      var pos = FIGS.map(function () { return { x: mL + rnd() * iw, y: mT + rnd() * ih }; });
      var ITER = 260;
      for (var it = 0; it < ITER; it++) {
        var disp = pos.map(function () { return { x: 0, y: 0 }; });
        for (var i = 0; i < pos.length; i++) for (var j = i + 1; j < pos.length; j++) {
          var dx = pos[i].x - pos[j].x, dy = pos[i].y - pos[j].y, d = Math.hypot(dx, dy) || 0.01;
          var rep = (k * k) / d;
          var ux = dx / d, uy = dy / d;
          disp[i].x += ux * rep; disp[i].y += uy * rep;
          disp[j].x -= ux * rep; disp[j].y -= uy * rep;
        }
        EDGES.forEach(function (e) {
          var a = pos[e[0]], b = pos[e[1]];
          var dx = a.x - b.x, dy = a.y - b.y, d = Math.hypot(dx, dy) || 0.01;
          var att = (d * d) / k * (0.4 + 0.6 * e[2]);
          var ux = dx / d, uy = dy / d;
          disp[e[0]].x -= ux * att; disp[e[0]].y -= uy * att;
          disp[e[1]].x += ux * att; disp[e[1]].y += uy * att;
        });
        var temp = (k * 0.28) * (1 - it / ITER);
        for (var m = 0; m < pos.length; m++) {
          disp[m].x += (cx - pos[m].x) * 0.02; disp[m].y += (cy - pos[m].y) * 0.02;
          var dl = Math.hypot(disp[m].x, disp[m].y) || 0.01, lim = Math.min(dl, temp);
          pos[m].x += (disp[m].x / dl) * lim; pos[m].y += (disp[m].y / dl) * lim;
          pos[m].x = Math.max(mL, Math.min(W - mR, pos[m].x));
          pos[m].y = Math.max(mT, Math.min(H - mB, pos[m].y));
        }
      }
      return pos;
    }

    function make() {
      var pos = layout();
      nodes = FIGS.map(function (f, i) {
        return { i: i, name: f.n, sid: f.sid, dt: dates(f), prom: !!f.p, col: f.c, id: f.id,
          s: f.s || null, fac: (typeof f.f === 'number' ? f.f : 0),
          r: radius(f), bx: pos[i].x, by: pos[i].y, x: pos[i].x, y: pos[i].y,
          ph: Math.random() * 6.2832 };
      });
    }
    function size() {
      W = hero.clientWidth; H = hero.clientHeight;
      cv.width = W * DPR; cv.height = H * DPR; ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
      make();
    }

    function label(p, bright) {
      ctx.textBaseline = 'middle';
      var nameFont = p.prom ? "500 13px 'EB Garamond', serif" : "400 10px 'Source Sans 3', sans-serif";
      var dtFont   = p.prom ? "400 11px 'EB Garamond', serif" : "400 9px 'Source Sans 3', sans-serif";
      ctx.font = nameFont; var nw = ctx.measureText(p.name).width;
      ctx.font = dtFont;   var dw = p.dt ? ctx.measureText('  ' + p.dt).width : 0;
      var pad = p.r + 5, total = nw + dw;
      var lx = (p.x + pad + total > W - 6) ? p.x - pad - total : p.x + pad;
      var aName = p.prom ? 0.92 : 0.46, aDt = p.prom ? 0.55 : 0.3;
      if (bright) { aName = Math.min(1, aName + 0.35); aDt = Math.min(0.85, aDt + 0.35); }
      ctx.font = nameFont;
      ctx.fillStyle = 'rgba(255,255,255,' + aName + ')';
      ctx.fillText(p.name, lx, p.y);
      if (p.dt) { ctx.font = dtFont;
        ctx.fillStyle = 'rgba(210,222,242,' + aDt + ')';
        ctx.fillText('  ' + p.dt, lx + nw, p.y); }
    }

    function draw() {
      ctx.clearRect(0, 0, W, H);
      var focus = hoverIdx >= 0;
      var sf = schoolHover || schoolActive;      // active school key, or null
      var sfocus = !focus && !!sf;               // school-highlight mode (node hover wins)
      // edges (real backbone)
      for (var e = 0; e < EDGES.length; e++) {
        var a = nodes[EDGES[e][0]], b = nodes[EDGES[e][1]], w = EDGES[e][2];
        var on = focus && (EDGES[e][0] === hoverIdx || EDGES[e][1] === hoverIdx);
        var both = sfocus && a.s === sf && b.s === sf;   // intra-school edge
        var al = (0.09 + 0.30 * w) * (focus ? (on ? 1.7 : 0.35) : (sfocus ? (both ? 1.5 : 0.16) : 1));
        ctx.strokeStyle = on   ? hexa(GOLD, Math.min(0.8, 0.4 + 0.5 * w))
                        : both ? hexa(a.col, Math.min(0.72, 0.38 + 0.4 * w))
                        : 'rgba(120,145,195,' + Math.min(0.6, al).toFixed(3) + ')';
        ctx.lineWidth = (0.6 + 1.3 * w) * (on ? 1.6 : both ? 1.4 : 1);
        ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.stroke();
      }
      // nodes
      for (var k = 0; k < nodes.length; k++) {
        var p = nodes[k];
        var dim = focus ? (k !== hoverIdx && neigh.indexOf(k) < 0)
                : sfocus ? (p.s !== sf)
                : false;
        var fa = dim ? 0.32 : 1;
        if (p.prom) {
          ctx.save(); ctx.shadowColor = hexa(p.col, 0.5 * fa); ctx.shadowBlur = 9;
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, 6.2832); ctx.fillStyle = hexa(p.col, 0.98 * fa); ctx.fill(); ctx.restore();
          // gold luminary ring (with its own glow so it reads on gold-ish nodes)
          ctx.save(); ctx.shadowColor = hexa(GOLD, 0.55 * fa); ctx.shadowBlur = (k === hoverIdx) ? 12 : 6;
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r + 3.5, 0, 6.2832);
          ctx.strokeStyle = hexa(GOLD, (k === hoverIdx ? 0.95 : 0.7) * fa); ctx.lineWidth = 1.4; ctx.stroke(); ctx.restore();
        } else {
          ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, 6.2832); ctx.fillStyle = hexa(p.col, 0.9 * fa); ctx.fill();
          if (k === hoverIdx) { ctx.beginPath(); ctx.arc(p.x, p.y, p.r + 3, 0, 6.2832);
            ctx.strokeStyle = hexa(GOLD, 0.85); ctx.lineWidth = 1.2; ctx.stroke(); }
        }
        var bright = (k === hoverIdx) || (focus && neigh.indexOf(k) >= 0) || (sfocus && p.s === sf);
        // Desktop shows all labels (text lives to the left, no collision). Mobile
        // has the text over the constellation, so draw labels ONLY for the
        // tapped/focused node + its neighbours — tap-to-inspect surfaces the rest.
        var drawLbl = canHover ? (!dim || p.prom) : bright;
        if (drawLbl) label(p, bright);
      }
    }

    function step(dt) {
      t += dt;
      for (var k = 0; k < nodes.length; k++) {
        var p = nodes[k];
        p.x = p.bx + Math.cos(t * 0.0016 + p.ph) * 4.0;
        p.y = p.by + Math.sin(t * 0.0014 + p.ph) * 4.0;
      }
    }
    var last = 0;
    function loop(ts) {
      var dt = last ? (ts - last) : 16; last = ts;
      if (!paused) step(dt);
      draw();
      raf = requestAnimationFrame(loop);
    }
    function start() { if (raf) cancelAnimationFrame(raf); last = 0; if (reduce) { draw(); return; } raf = requestAnimationFrame(loop); }

    // ── hover-to-pause + click → Stammbaum (desktop only) ──
    function pickAt(clientX, clientY, slop) {
      slop = slop || 9;
      var rect = cv.getBoundingClientRect();
      var mx = clientX - rect.left, my = clientY - rect.top, best = -1, bd = 1e9;
      for (var k = 0; k < nodes.length; k++) {
        var d = Math.hypot(nodes[k].x - mx, nodes[k].y - my);
        if (d < nodes[k].r + slop && d < bd) { bd = d; best = k; }
      }
      return best;
    }
    function pick(ev) { return pickAt(ev.clientX, ev.clientY); }

    // ── tooltip: fill / clamp-to-viewport / show / hide ──
    function fillTip(p, tap) {
      if (!tip) return;
      var swatch = '<i style="background:' + p.col + '"></i>';
      var pct = Math.max(3, Math.min(100, Math.round(p.fac)));
      var foot = tap
        ? (p.sid
            ? '<button type="button" class="hero-tip-go" data-key="' + (p.sid || p.name) + '">' + tr('openTap') + ' \u2192</button>'
            : '<div class="hero-tip-hint off">' + tr('notree') + '</div>')
        : (p.sid
            ? '<div class="hero-tip-hint">' + tr('open') + '</div>'
            : '<div class="hero-tip-hint off">' + tr('notree') + '</div>');
      tip.innerHTML =
        (tap ? '<button type="button" class="hero-tip-close" aria-label="' + tr('close') + '">\u00d7</button>' : '') +
        '<div class="hero-tip-name">' + p.name + '</div>' +
        (p.dt ? '<div class="hero-tip-dates">' + p.dt + '</div>' : '') +
        '<div class="hero-tip-school">' + swatch + schoolLabel(p.s) + '</div>' +
        (p.prom ? '<div class="hero-tip-badge">\u2726 ' + tr('luminary') + '</div>' : '') +
        '<div class="hero-tip-prom">' + tr('prominence') + '</div>' +
        '<div class="hero-tip-bar"><span style="width:' + pct + '%"></span></div>' +
        foot;
    }
    function moveTip(ev) {
      if (!tip) return;
      var tw = tip.offsetWidth || 240, th = tip.offsetHeight || 130;
      var x = Math.min(ev.clientX + 16, window.innerWidth - tw - 8);
      var y = Math.min(Math.max(ev.clientY - th / 2, 8), window.innerHeight - th - 8);
      tip.style.left = x + 'px'; tip.style.top = y + 'px';
    }
    function showTip() { if (tip) tip.classList.add('show'); }
    function hideTip() { if (tip) tip.classList.remove('show'); }

    // ── interactive school legend (real HTML → keyboard + touch accessible) ──
    var legendEl = null;
    function schoolGroups() {
      var seen = {}, order = [];
      FIGS.forEach(function (f) {
        var key = f.s || '\u0000';                 // null school → single fallback bucket
        if (!seen[key]) { seen[key] = { key: f.s || null, col: f.c, n: 0 }; order.push(key); }
        seen[key].n++;
      });
      return order.map(function (k) { return seen[k]; }).sort(function (a, b) { return b.n - a.n; });
    }
    function syncLegend() {
      if (!legendEl) return;
      if (schoolActive) legendEl.setAttribute('data-active', '1'); else legendEl.removeAttribute('data-active');
      var chips = legendEl.querySelectorAll('.hero-legend-chip');
      for (var i = 0; i < chips.length; i++) {
        chips[i].classList.toggle('on', !!schoolActive && chips[i].getAttribute('data-school') === schoolActive);
      }
    }
    function setSchool(s, sticky) {
      if (sticky) { schoolActive = (schoolActive === s) ? null : s; schoolHover = null; }
      else { schoolHover = s; }
      syncLegend();
      if (reduce) draw();
    }
    function clearHover(s) { if (schoolHover === s) { schoolHover = null; if (reduce) draw(); } }
    function buildLegend() {
      if (!inner) return;
      var groups = schoolGroups();
      // pre-regen safety: if figures carry no school, there is nothing to key on
      if (!groups.length || (groups.length === 1 && groups[0].key === null)) return;
      if (!legendEl) {
        legendEl = document.createElement('div');
        legendEl.className = 'hero-legend';
        legendEl.setAttribute('role', 'group');
        inner.appendChild(legendEl);
      }
      legendEl.setAttribute('aria-label', tr('legendAria'));
      legendEl.innerHTML = '';
      groups.forEach(function (g) {
        var b = document.createElement('button');
        b.type = 'button';
        b.className = 'hero-legend-chip';
        b.setAttribute('data-school', g.key || '');
        b.style.pointerEvents = 'auto';           // .hero-inner is pointer-none on desktop; re-enable per chip
        b.innerHTML = '<i style="background:' + g.col + '"></i>' + schoolLabel(g.key);
        if (canHover) {
          b.addEventListener('mouseenter', function () { setSchool(g.key, false); });
          b.addEventListener('mouseleave', function () { clearHover(g.key); });
          b.addEventListener('focus',      function () { setSchool(g.key, false); });
          b.addEventListener('blur',       function () { clearHover(g.key); });
        }
        b.addEventListener('click', function () { setSchool(g.key, true); });
        legendEl.appendChild(b);
      });
      syncLegend();
    }

    if (canHover) {
      cv.addEventListener('mousemove', function (ev) {
        paused = true;
        var h = pick(ev);
        if (h !== hoverIdx) { hoverIdx = h; neigh = h >= 0 ? ADJ[h] : []; if (h >= 0) fillTip(nodes[h]); }
        cv.style.cursor = h >= 0 ? 'pointer' : 'default';
        if (h >= 0) { showTip(); moveTip(ev); } else { hideTip(); }
        if (reduce) draw();
      });
      cv.addEventListener('mouseleave', function () {
        paused = false; hoverIdx = -1; neigh = []; cv.style.cursor = 'default'; hideTip(); if (reduce) draw();
      });
      cv.addEventListener('click', function (ev) {
        var h = pick(ev);
        if (h < 0) return;
        var key = nodes[h].sid || nodes[h].name;   // sid = exact Stammbaum id; name = graceful fallback
        window.location.href = 'analytics.html#stammbaum=' + encodeURIComponent(key);
      });
    } else {
      // ── mobile: tap-to-inspect ────────────────────────────────────────────
      // A single, still tap on a node opens an interactive card (info + Stammbaum
      // button); a scroll-drag or a tap on empty space never claims the gesture,
      // so the page scrolls normally past the hero.
      function positionCard(x, y) {
        if (!tip) return;
        var tw = tip.offsetWidth || 240, th = tip.offsetHeight || 150;
        var left = Math.min(Math.max(8, x - tw / 2), window.innerWidth - tw - 8);
        var top = y - th - 18;                                     // prefer above the finger
        if (top < 8) top = Math.min(y + 24, window.innerHeight - th - 8);
        tip.style.left = left + 'px'; tip.style.top = top + 'px';
      }
      function selectNode(h, x, y) {
        hoverIdx = h; neigh = ADJ[h] || []; paused = true;        // freeze so the node stays under the card
        fillTip(nodes[h], true); showTip(); positionCard(x, y);
        if (reduce) draw();
      }
      function dismissCard() {
        hoverIdx = -1; neigh = []; paused = false; hideTip();
        if (reduce) draw();
      }
      var tsX = 0, tsY = 0, tMoved = false;
      cv.addEventListener('touchstart', function (ev) {
        if (ev.touches.length !== 1) { tMoved = true; return; }
        tMoved = false; tsX = ev.touches[0].clientX; tsY = ev.touches[0].clientY;
      }, { passive: true });
      cv.addEventListener('touchmove', function (ev) {
        if (ev.touches.length !== 1) { tMoved = true; return; }
        var dx = ev.touches[0].clientX - tsX, dy = ev.touches[0].clientY - tsY;
        if (dx * dx + dy * dy > 100) tMoved = true;                // >10px travel = scroll, not a tap
      }, { passive: true });
      cv.addEventListener('touchend', function (ev) {
        if (tMoved) return;                                        // scroll gesture → leave the page alone
        var tch = ev.changedTouches[0];
        var h = pickAt(tch.clientX, tch.clientY, 16);              // wider slop for fingers
        if (h >= 0) { ev.preventDefault(); selectNode(h, tch.clientX, tch.clientY); }
        else { dismissCard(); }                                    // tap on empty space closes the card
      }, { passive: false });
      if (tip) {
        tip.addEventListener('click', function (ev) {
          var go = ev.target.closest('.hero-tip-go');
          if (go) { window.location.href = 'analytics.html#stammbaum=' + encodeURIComponent(go.getAttribute('data-key')); return; }
          if (ev.target.closest('.hero-tip-close')) dismissCard();
        });
      }
      window.addEventListener('scroll', function () { if (hoverIdx >= 0) dismissCard(); }, { passive: true });
    }

    // Mount content that contributes to hero height FIRST, so the canvas is
    // sized against the final layout (the legend + rotator reserve both add
    // height; sizing before them left the bitmap short and vertically stretched).
    initRotator();
    buildLegend();

    window.addEventListener('resize', function () { size(); start(); });
    size(); start();

    // Fonts change text metrics → hero height; re-size (not just redraw) so the
    // backing store stays matched. Deterministic layout means no reshuffle.
    if (document.fonts && document.fonts.ready) { document.fonts.ready.then(function () { size(); }); }

    // Keep the canvas backing store matched to the content-driven hero size
    // (legend wrap, rotator reserve, orientation). rAF-coalesced; size() never
    // changes the hero's own size, so this can't loop.
    if (window.ResizeObserver) {
      var roPending = false;
      var ro = new ResizeObserver(function () {
        if (roPending) return;
        roPending = true;
        requestAnimationFrame(function () { roPending = false; size(); });
      });
      ro.observe(hero);
    }

    window.addEventListener('agw-lang-change', function () {
      buildLegend();                                                   // relabel chips for the new language
      if (hoverIdx >= 0 && nodes[hoverIdx]) fillTip(nodes[hoverIdx]);  // refresh an open tooltip
    });
  }

  // ── "Was uns beschäftigt" rotator — recent Jahrestagung themes from ARCHIVE ──
  function initRotator() {
    var el = document.getElementById('hero-rot-theme');
    if (!el) return;
    if (typeof ARCHIVE === 'undefined') return;
    var box = (el.closest && el.closest('.hero-rotator')) || el.parentNode;
    var reduceR = window.matchMedia && window.matchMedia('(prefers-reduced-motion:reduce)').matches;
    function lang() { return (window.AGW && window.AGW.getLang) ? window.AGW.getLang() : 'de'; }
    function themes() {
      var de = lang() !== 'en';
      return ARCHIVE.filter(function (c) { return c.theme; })
        .slice().sort(function (a, b) { return (b.year || 0) - (a.year || 0); })
        .slice(0, 6)
        .map(function (c) { return (de ? c.theme : (c.theme_en || c.theme)) + ' (' + c.year + ')'; });
    }
    var list = themes(), ti = 0, timer = null, paused = false;

    // Reserve the height of the TALLEST theme and centre within it, so rotation
    // never reflows the page — full titles kept, no truncation.
    function measure() {
      if (!box) return;
      var keep = el.textContent, prevTrans = el.style.transition;
      el.style.transition = 'none'; box.style.height = 'auto';
      var max = 0;
      for (var i = 0; i < list.length; i++) { el.textContent = list[i]; if (box.offsetHeight > max) max = box.offsetHeight; }
      el.textContent = keep;
      box.style.alignContent = 'center';
      box.style.height = max ? max + 'px' : '';
      el.style.transition = prevTrans;
    }
    function show() { el.textContent = list[ti] || ''; }
    // dwell scales with length so long conference titles stay up long enough to read
    function dwell() { return Math.min(9000, Math.max(3200, 2600 + (list[ti] || '').length * 45)); }
    function schedule() { clearTimeout(timer); if (reduceR || paused || list.length < 2) return; timer = setTimeout(step, dwell()); }
    function step() {
      el.style.opacity = 0;
      setTimeout(function () { ti = (ti + 1) % list.length; show(); el.style.opacity = 1; schedule(); }, 500);
    }

    show(); measure(); schedule();

    window.addEventListener('agw-lang-change', function () { list = themes(); if (ti >= list.length) ti = 0; show(); measure(); schedule(); });
    window.addEventListener('resize', measure);
    if (document.fonts && document.fonts.ready) { document.fonts.ready.then(measure); }
    if (box) {                                   // pause on hover so long titles can be read in full
      box.addEventListener('mouseenter', function () { paused = true; clearTimeout(timer); });
      box.addEventListener('mouseleave', function () { paused = false; schedule(); });
    }
  }

  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', init); }
  else { init(); }
})();
