#!/usr/bin/env python3
"""
hero_data.py — regenerate the embedded constellation data in agw_hero_viz.js
═══════════════════════════════════════════════════════════════════════════
Reads the validated corpus + the BODY-only proximity matrix and rewrites the
delimited data block in agw_hero_viz.js in place. Run whenever the corpus or
proximity changes; the hero stays a single dependency-free static file (no
runtime fetch), exactly like the curated version it replaces.

    python tools/hero_data.py \
        --corpus data/agw_corpus.json \
        --proximity data/agw_proximity_body.json \
        --hero agw_hero_viz.js

Selection (all one-line tunables below):
  • TOP_N        nodes, by prominence.factor (the validated scalar)
  • LUMINARIES   = top-N_LUM by factor → gold ring + prominent label
  • PIN          fids always included even if below the factor cutoff
  • EDGE_PER_NODE strongest body co-occurrence links kept per node (backbone)

Node size in the hero is derived from `f` (factor) at render time, so it is a
render tunable, not baked here.
"""
import sys, json, re, argparse, unicodedata
from pathlib import Path

TOP_N        = 34
N_LUM        = 10          # luminaries (gold ring) = top-N_LUM by factor …
LUM_EXTRA    = []          # …plus any fids listed here, regardless of rank (explicit picks)
PIN          = ['losch-august']      # Lösch is #32 by factor; pin guarantees the Raumwirtschaft strand survives a rebuild
EDGE_PER_NODE = 3

# Canonical school palette — lifted for a dark background, copied verbatim from
# agw_schools_net.js so the hero and the Schulen panel speak one colour language.
COLORS = {
    "Austrian School": "#3FB0A3", "Classical": "#C2A06B", "Contemporary": "#bab0ac",
    "Development Economics": "#a0cbe8", "Evolutionary": "#edc948",
    "Historical School": "#6E8FCB", "Institutional": "#e79ab0", "Keynesian": "#6BB58C",
    "Marxist": "#b07aa1", "Neoclassical": "#9AA6D0", "Ordoliberalismus": "#D6A24A",
    "Philosophy": "#d4a6c8", "Post-Keynesian/Sraffian": "#7fb3c9",
    "Raumwirtschaftslehre": "#8cd17d",
}
FALLBACK = "#8892A6"                  # "ohne Zuordnung" / Other / unmatched school

# fid → short display name, only where last-token is wrong (none in the current
# top-34, but keeps the generator correct if the roster grows).
SHORT_OVERRIDES = {}

BEGIN = "/* @@HERO-DATA:BEGIN — generated by tools/hero_data.py, do not edit by hand @@ */"
END   = "/* @@HERO-DATA:END@@ */"

def short_name(fid, name):
    if fid in SHORT_OVERRIDES:
        return SHORT_OVERRIDES[fid]
    return name.split()[-1]

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--corpus',     type=Path, default=Path('tools/agw_corpus.json'))
    ap.add_argument('--proximity',  type=Path, default=Path('tools/agw_proximity_body.json'))
    ap.add_argument('--lineage',    type=Path, default=Path('agw_lineage_data.js'))
    ap.add_argument('--hero',       type=Path, default=Path('agw_hero_viz.js'))
    args = ap.parse_args()

    # Stammbaum id resolution: map each hero figure to its exact agw_lineage_data.js
    # id at BUILD time (deterministic; disambiguates e.g. Max vs Alfred Weber), so the
    # hero click can deep-link straight to data-id="<sid>" with no runtime guessing.
    by_full, by_name = {}, {}
    if args.lineage.exists():
        lg = args.lineage.read_text(encoding='utf-8')
        for lid, lname, lfull in re.findall(
                r'"id":\s*"([^"]+)",\s*"name":\s*"([^"]*)",\s*"full":\s*"([^"]*)"', lg):
            by_full[lfull.lower()] = lid
            by_name.setdefault(lname.lower(), []).append(lid)

    def stammbaum_id(fid, full):
        sid = by_full.get(full.lower())
        if sid: return sid                       # exact full name — unambiguous
        cand = by_name.get(short_name(fid, full).lower(), [])
        return cand[0] if len(cand) == 1 else None  # unique short name, else leave unlinked

    corpus = json.loads(args.corpus.read_text(encoding='utf-8'))
    figs = [r for r in corpus['figures'] if r['prominence'].get('factor') is not None]
    figs.sort(key=lambda r: -r['prominence']['factor'])

    # node set: top-N by factor, then ensure pinned fids are present
    chosen = figs[:TOP_N]
    have = {r['fid'] for r in chosen}
    for fid in PIN:
        if fid not in have:
            extra = next((r for r in figs if r['fid'] == fid), None)
            if extra: chosen.append(extra); have.add(fid)

    lum = {r['fid'] for r in figs[:N_LUM]} | set(LUM_EXTRA)

    # scale factor to a 0..100 span for the hero (max = 100 already, but be robust)
    fmax = max(r['prominence']['factor'] for r in chosen) or 1
    FIGS = []
    for r in chosen:
        FIGS.append({
            "n": short_name(r['fid'], r['name']),
            "b": r.get('birth'), "d": r.get('death'),
            "c": COLORS.get(r.get('school'), FALLBACK),
            "s": r.get('school') or None,          # school name → hero legend + tooltip
            "p": 1 if r['fid'] in lum else 0,
            "f": round(100 * r['prominence']['factor'] / fmax, 1),
            "id": r['fid'],
            "sid": stammbaum_id(r['fid'], r['name']),   # agw_lineage_data.js id, or null if not in the Stammbaum
        })

    # edges: body co-occurrence backbone among the chosen nodes
    P = json.loads(args.proximity.read_text(encoding='utf-8'))
    W = P.get('W') or {}
    idx = {f['id']: i for i, f in enumerate(FIGS)}
    edge_w = {}                                   # (i,j) i<j -> weight
    for f in FIGS:
        a = f['id']; row = W.get(a, {})
        links = sorted(((b, w) for b, w in row.items() if b in idx and b != a),
                       key=lambda kv: -kv[1])[:EDGE_PER_NODE]
        for b, w in links:
            i, j = sorted((idx[a], idx[b]))
            edge_w[(i, j)] = max(edge_w.get((i, j), 0.0), float(w))
    wmax = max(edge_w.values()) if edge_w else 1.0
    EDGES = [[i, j, round(w / wmax, 3)] for (i, j), w in
             sorted(edge_w.items(), key=lambda kv: -kv[1])]

    # emit compact JS
    figs_js = ",\n    ".join(json.dumps(f, ensure_ascii=False) for f in FIGS)
    edges_js = ", ".join(f"[{i},{j},{w}]" for i, j, w in EDGES)
    block = (f"{BEGIN}\n"
             f"  var FIGS = [\n    {figs_js}\n  ];\n"
             f"  var EDGES = [{edges_js}];\n"
             f"  {END}")

    src = args.hero.read_text(encoding='utf-8')
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(src):
        sys.exit(f"ERROR: data markers not found in {args.hero}. Expected {BEGIN} … {END}.")
    out = pat.sub(lambda _: block, src)
    args.hero.write_text(out, encoding='utf-8')

    print(f"wrote {args.hero}: {len(FIGS)} figures ({sum(f['p'] for f in FIGS)} luminaries), "
          f"{len(EDGES)} backbone edges")
    print("luminaries:", ", ".join(f['n'] for f in FIGS if f['p']))
    print("pinned present:", ", ".join(f for f in PIN if f in idx) or "(none)")
    linked = [f['n'] for f in FIGS if f['sid']]
    unlinked = [f['n'] for f in FIGS if not f['sid']]
    print(f"Stammbaum-linked ({len(linked)}/{len(FIGS)}): click focuses the figure")
    if unlinked:
        print(f"  not in Stammbaum ({len(unlinked)}): click opens panel unfocused — {', '.join(unlinked)}")

if __name__ == '__main__':
    main()
